package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.DistributeQuestionDel;
import com.work.shop.oms.bean.DistributeQuestionDelExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DistributeQuestionDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(DistributeQuestionDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(DistributeQuestionDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int insert(DistributeQuestionDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(DistributeQuestionDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @ReadOnly
    List<DistributeQuestionDel> selectByExample(DistributeQuestionDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    DistributeQuestionDel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") DistributeQuestionDel record, @Param("example") DistributeQuestionDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") DistributeQuestionDel record, @Param("example") DistributeQuestionDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(DistributeQuestionDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_question_del
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(DistributeQuestionDel record);
}