package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.DistributeAction;
import com.work.shop.oms.bean.DistributeActionExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DistributeActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(DistributeActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(DistributeActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int insert(DistributeAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(DistributeAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @ReadOnly
    List<DistributeAction> selectByExampleWithBLOBs(DistributeActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @ReadOnly
    List<DistributeAction> selectByExample(DistributeActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    DistributeAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") DistributeAction record, @Param("example") DistributeActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") DistributeAction record, @Param("example") DistributeActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") DistributeAction record, @Param("example") DistributeActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(DistributeAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(DistributeAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(DistributeAction record);
}