package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.HandOrderInfo;
import com.work.shop.oms.bean.HandOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HandOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(HandOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(HandOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int insert(HandOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(HandOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @ReadOnly
    List<HandOrderInfo> selectByExample(HandOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    HandOrderInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") HandOrderInfo record, @Param("example") HandOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") HandOrderInfo record, @Param("example") HandOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(HandOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hand_order_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(HandOrderInfo record);
}