package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.MasterOrderActionHistory;
import com.work.shop.oms.bean.MasterOrderActionHistoryExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterOrderActionHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MasterOrderActionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MasterOrderActionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int insert(MasterOrderActionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MasterOrderActionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MasterOrderActionHistory> selectByExampleWithBLOBs(MasterOrderActionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MasterOrderActionHistory> selectByExample(MasterOrderActionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    MasterOrderActionHistory selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MasterOrderActionHistory record, @Param("example") MasterOrderActionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") MasterOrderActionHistory record, @Param("example") MasterOrderActionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MasterOrderActionHistory record, @Param("example") MasterOrderActionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MasterOrderActionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(MasterOrderActionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_action_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MasterOrderActionHistory record);
}