package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.MasterOrderGoodsHistory;
import com.work.shop.oms.bean.MasterOrderGoodsHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterOrderGoodsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MasterOrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MasterOrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int insert(MasterOrderGoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MasterOrderGoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MasterOrderGoodsHistory> selectByExample(MasterOrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    MasterOrderGoodsHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MasterOrderGoodsHistory record, @Param("example") MasterOrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MasterOrderGoodsHistory record, @Param("example") MasterOrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MasterOrderGoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MasterOrderGoodsHistory record);
}