package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.MasterOrderAddressInfo;
import com.work.shop.oms.bean.MasterOrderAddressInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterOrderAddressInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MasterOrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MasterOrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String masterOrderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int insert(MasterOrderAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MasterOrderAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MasterOrderAddressInfo> selectByExample(MasterOrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    MasterOrderAddressInfo selectByPrimaryKey(String masterOrderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MasterOrderAddressInfo record, @Param("example") MasterOrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MasterOrderAddressInfo record, @Param("example") MasterOrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MasterOrderAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MasterOrderAddressInfo record);
}