package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.MasterOrderAddressInfoHistory;
import com.work.shop.oms.bean.MasterOrderAddressInfoHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterOrderAddressInfoHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MasterOrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MasterOrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String masterOrderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int insert(MasterOrderAddressInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MasterOrderAddressInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MasterOrderAddressInfoHistory> selectByExample(MasterOrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    MasterOrderAddressInfoHistory selectByPrimaryKey(String masterOrderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MasterOrderAddressInfoHistory record, @Param("example") MasterOrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MasterOrderAddressInfoHistory record, @Param("example") MasterOrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MasterOrderAddressInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MasterOrderAddressInfoHistory record);
}