package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderGoodsHistory;
import com.work.shop.oms.bean.OrderGoodsHistoryExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderGoodsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderGoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderGoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderGoodsHistory> selectByExampleWithBLOBs(OrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderGoodsHistory> selectByExample(OrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    OrderGoodsHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderGoodsHistory record, @Param("example") OrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") OrderGoodsHistory record, @Param("example") OrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderGoodsHistory record, @Param("example") OrderGoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderGoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(OrderGoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderGoodsHistory record);
}