package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderReturn;
import com.work.shop.oms.bean.OrderReturnExample;
import java.util.List;

import com.work.shop.oms.bean.OrderReturnMoneyBean;
import org.apache.ibatis.annotations.Param;

public interface OrderReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String returnSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderReturn> selectByExampleWithBLOBs(OrderReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderReturn> selectByExample(OrderReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    OrderReturn selectByPrimaryKey(String returnSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderReturn record, @Param("example") OrderReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") OrderReturn record, @Param("example") OrderReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderReturn record, @Param("example") OrderReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(OrderReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderReturn record);

    /**
     * 获取订单退单金额状态信息
     * @param masterOrderSn
     * @return
     */
    @ReadOnly
    List<OrderReturnMoneyBean> getOrderReturnSettlementList(String masterOrderSn);
}