package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderReturnShip;
import com.work.shop.oms.bean.OrderReturnShipExample;

public interface OrderReturnShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderReturnShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderReturnShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String relatingReturnSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderReturnShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderReturnShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderReturnShip> selectByExample(OrderReturnShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    OrderReturnShip selectByPrimaryKey(String relatingReturnSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderReturnShip record, @Param("example") OrderReturnShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderReturnShip record, @Param("example") OrderReturnShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderReturnShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderReturnShip record);
}