package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderPeriodDetail;
import com.work.shop.oms.bean.OrderPeriodDetailExample;
import com.work.shop.oms.bean.OrderPeriodDetailKey;

public interface OrderPeriodDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderPeriodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderPeriodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(OrderPeriodDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderPeriodDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderPeriodDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderPeriodDetail> selectByExample(OrderPeriodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    OrderPeriodDetail selectByPrimaryKey(OrderPeriodDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderPeriodDetail record, @Param("example") OrderPeriodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderPeriodDetail record, @Param("example") OrderPeriodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderPeriodDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_period_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderPeriodDetail record);
}