package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderBillList;
import com.work.shop.oms.bean.OrderBillListExample;

public interface OrderBillListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderBillListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderBillListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String billNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderBillList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderBillList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderBillList> selectByExample(OrderBillListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    OrderBillList selectByPrimaryKey(String billNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderBillList record, @Param("example") OrderBillListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderBillList record, @Param("example") OrderBillListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderBillList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderBillList record);
}