package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderReturnGoods;
import com.work.shop.oms.bean.OrderReturnGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderReturnGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderReturnGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderReturnGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderReturnGoods> selectByExample(OrderReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    OrderReturnGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderReturnGoods record, @Param("example") OrderReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderReturnGoods record, @Param("example") OrderReturnGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderReturnGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderReturnGoods record);
}