package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderExpressCompany;
import com.work.shop.oms.bean.OrderExpressCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderExpressCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderExpressCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderExpressCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderExpressCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderExpressCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderExpressCompany> selectByExample(OrderExpressCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    OrderExpressCompany selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderExpressCompany record, @Param("example") OrderExpressCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderExpressCompany record, @Param("example") OrderExpressCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderExpressCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderExpressCompany record);
}