package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderAttachment;
import com.work.shop.oms.bean.OrderAttachmentExample;

public interface OrderAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderAttachment> selectByExample(OrderAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    OrderAttachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderAttachment record, @Param("example") OrderAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderAttachment record, @Param("example") OrderAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attachment
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderAttachment record);
}