package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderInfoExtend;
import com.work.shop.oms.bean.OrderInfoExtendExample;

public interface OrderInfoExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderInfoExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderInfoExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String orderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderInfoExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderInfoExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderInfoExtend> selectByExample(OrderInfoExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    OrderInfoExtend selectByPrimaryKey(String orderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderInfoExtend record, @Param("example") OrderInfoExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderInfoExtend record, @Param("example") OrderInfoExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderInfoExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_extend
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderInfoExtend record);
}