package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderAction;
import com.work.shop.oms.bean.OrderActionExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderAction> selectByExampleWithBLOBs(OrderActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderAction> selectByExample(OrderActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    OrderAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderAction record, @Param("example") OrderActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") OrderAction record, @Param("example") OrderActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderAction record, @Param("example") OrderActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(OrderAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderAction record);
}