package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderInfoHistory;
import com.work.shop.oms.bean.OrderInfoHistoryExample;

public interface OrderInfoHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String orderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderInfoHistory> selectByExample(OrderInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    OrderInfoHistory selectByPrimaryKey(String orderSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderInfoHistory record, @Param("example") OrderInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderInfoHistory record, @Param("example") OrderInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderInfoHistory record);
}