package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderAddressInfo;
import com.work.shop.oms.bean.OrderAddressInfoExample;

public interface OrderAddressInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderAddressInfo> selectByExample(OrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    OrderAddressInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderAddressInfo record, @Param("example") OrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderAddressInfo record, @Param("example") OrderAddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderAddressInfo record);
}