package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderRefund;
import com.work.shop.oms.bean.OrderRefundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String returnPaySn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderRefund> selectByExample(OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    OrderRefund selectByPrimaryKey(String returnPaySn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderRefund record, @Param("example") OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderRefund record, @Param("example") OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderRefund record);
}