package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderGoodsChargeBack;
import com.work.shop.oms.bean.OrderGoodsChargeBackExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderGoodsChargeBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderGoodsChargeBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderGoodsChargeBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderGoodsChargeBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderGoodsChargeBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderGoodsChargeBack> selectByExample(OrderGoodsChargeBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    OrderGoodsChargeBack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderGoodsChargeBack record, @Param("example") OrderGoodsChargeBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderGoodsChargeBack record, @Param("example") OrderGoodsChargeBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderGoodsChargeBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_charge_back
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderGoodsChargeBack record);
}