package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderTaskConfig;
import com.work.shop.oms.bean.OrderTaskConfigExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderTaskConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderTaskConfig> selectByExample(OrderTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    OrderTaskConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderTaskConfig record, @Param("example") OrderTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderTaskConfig record, @Param("example") OrderTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderTaskConfig record);
}