package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderAddressInfoHistory;
import com.work.shop.oms.bean.OrderAddressInfoHistoryExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderAddressInfoHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderAddressInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderAddressInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderAddressInfoHistory> selectByExample(OrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    OrderAddressInfoHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderAddressInfoHistory record, @Param("example") OrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderAddressInfoHistory record, @Param("example") OrderAddressInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderAddressInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_info_history
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderAddressInfoHistory record);
}