package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderPickingList;
import com.work.shop.oms.bean.OrderPickingListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderPickingListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderPickingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderPickingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderPickingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderPickingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderPickingList> selectByExampleWithBLOBs(OrderPickingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderPickingList> selectByExample(OrderPickingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    OrderPickingList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderPickingList record, @Param("example") OrderPickingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") OrderPickingList record, @Param("example") OrderPickingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderPickingList record, @Param("example") OrderPickingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderPickingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(OrderPickingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_picking_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderPickingList record);
}