package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.OrderShip;
import com.work.shop.oms.bean.OrderShipExample;
import com.work.shop.oms.bean.OrderShipKey;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(OrderShipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderShip> selectByExample(OrderShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    OrderShip selectByPrimaryKey(OrderShipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderShip record, @Param("example") OrderShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderShip record, @Param("example") OrderShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_ship
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderShip record);
}