package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.api.bean.OrderReturnAction;
import com.work.shop.oms.bean.OrderReturnActionExample;

public interface OrderReturnActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OrderReturnActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OrderReturnActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int insert(OrderReturnAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OrderReturnAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OrderReturnAction> selectByExample(OrderReturnActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    OrderReturnAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OrderReturnAction record, @Param("example") OrderReturnActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OrderReturnAction record, @Param("example") OrderReturnActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OrderReturnAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_return_action
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OrderReturnAction record);
}