package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.PurchaseOrderLine;
import com.work.shop.oms.bean.PurchaseOrderLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseOrderLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PurchaseOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PurchaseOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int insert(PurchaseOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PurchaseOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PurchaseOrderLine> selectByExample(PurchaseOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    PurchaseOrderLine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PurchaseOrderLine record, @Param("example") PurchaseOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PurchaseOrderLine record, @Param("example") PurchaseOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(PurchaseOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(PurchaseOrderLine record);
}