package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.ReturnForward;
import com.work.shop.oms.bean.ReturnForwardExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReturnForwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ReturnForwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ReturnForwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int insert(ReturnForward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ReturnForward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ReturnForward> selectByExample(ReturnForwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    ReturnForward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ReturnForward record, @Param("example") ReturnForwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ReturnForward record, @Param("example") ReturnForwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ReturnForward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_forward
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ReturnForward record);
}