package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.ServerMqConfig;
import com.work.shop.oms.bean.ServerMqConfigExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerMqConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ServerMqConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ServerMqConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int insert(ServerMqConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ServerMqConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ServerMqConfig> selectByExample(ServerMqConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    ServerMqConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ServerMqConfig record, @Param("example") ServerMqConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ServerMqConfig record, @Param("example") ServerMqConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ServerMqConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_mq_config
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ServerMqConfig record);
}