package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.SystemPayment;
import com.work.shop.oms.bean.SystemPaymentExample;
import com.work.shop.oms.bean.SystemPaymentWithBLOBs;

public interface SystemPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SystemPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SystemPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Byte payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int insert(SystemPaymentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SystemPaymentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemPaymentWithBLOBs> selectByExampleWithBLOBs(SystemPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemPayment> selectByExample(SystemPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    SystemPaymentWithBLOBs selectByPrimaryKey(Byte payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SystemPaymentWithBLOBs record, @Param("example") SystemPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") SystemPaymentWithBLOBs record, @Param("example") SystemPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SystemPayment record, @Param("example") SystemPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SystemPaymentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(SystemPaymentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_payment
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(SystemPayment record);
}