package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.SystemRegionMatch;
import com.work.shop.oms.bean.SystemRegionMatchExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRegionMatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SystemRegionMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SystemRegionMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int insert(SystemRegionMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SystemRegionMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemRegionMatch> selectByExampleWithBLOBs(SystemRegionMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemRegionMatch> selectByExample(SystemRegionMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    SystemRegionMatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SystemRegionMatch record, @Param("example") SystemRegionMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") SystemRegionMatch record, @Param("example") SystemRegionMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SystemRegionMatch record, @Param("example") SystemRegionMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SystemRegionMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(SystemRegionMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region_match
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(SystemRegionMatch record);
}