package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.SystemOmsRole;
import com.work.shop.oms.bean.SystemOmsRoleExample;

public interface SystemOmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SystemOmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SystemOmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int insert(SystemOmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SystemOmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemOmsRole> selectByExampleWithBLOBs(SystemOmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemOmsRole> selectByExample(SystemOmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    SystemOmsRole selectByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SystemOmsRole record, @Param("example") SystemOmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") SystemOmsRole record, @Param("example") SystemOmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SystemOmsRole record, @Param("example") SystemOmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SystemOmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(SystemOmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_oms_role
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(SystemOmsRole record);
}