package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.SystemMasterOrderSn;
import com.work.shop.oms.bean.SystemMasterOrderSnExample;

public interface SystemMasterOrderSnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SystemMasterOrderSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SystemMasterOrderSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer autoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @Writer
    int insert(SystemMasterOrderSn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SystemMasterOrderSn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemMasterOrderSn> selectByExample(SystemMasterOrderSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SystemMasterOrderSn record, @Param("example") SystemMasterOrderSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_master_order_sn
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SystemMasterOrderSn record, @Param("example") SystemMasterOrderSnExample example);
}