package com.work.shop.oms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.SystemResource;
import com.work.shop.oms.bean.SystemResourceExample;

public interface SystemResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int insert(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemResource> selectByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    SystemResource selectByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SystemResource record, @Param("example") SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SystemResource record, @Param("example") SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(SystemResource record);
}