package com.work.shop.oms.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.oms.bean.UserPointsException;
import com.work.shop.oms.bean.UserPointsExceptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPointsExceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(UserPointsExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(UserPointsExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int insert(UserPointsException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(UserPointsException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @ReadOnly
    List<UserPointsException> selectByExampleWithBLOBs(UserPointsExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @ReadOnly
    List<UserPointsException> selectByExample(UserPointsExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    UserPointsException selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") UserPointsException record, @Param("example") UserPointsExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") UserPointsException record, @Param("example") UserPointsExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") UserPointsException record, @Param("example") UserPointsExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(UserPointsException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(UserPointsException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_points_exception
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(UserPointsException record);
}