package com.work.shop.oms.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class MasterOrderGoodsTemp implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -6824513882410582094L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.depot_code
     *
     * @mbggenerated
     */
    private String depotCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.master_order_sn
     *
     * @mbggenerated
     */
    private String masterOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.custom_code
     *
     * @mbggenerated
     */
    private String customCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.extension_code
     *
     * @mbggenerated
     */
    private String extensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.extension_id
     *
     * @mbggenerated
     */
    private String extensionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.goods_number
     *
     * @mbggenerated
     */
    private Short goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.goods_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.transaction_price
     *
     * @mbggenerated
     */
    private BigDecimal transactionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.settlement_price
     *
     * @mbggenerated
     */
    private BigDecimal settlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.discount
     *
     * @mbggenerated
     */
    private Float discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.integral_money
     *
     * @mbggenerated
     */
    private BigDecimal integralMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.goods_size_name
     *
     * @mbggenerated
     */
    private String goodsSizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.goods_color_name
     *
     * @mbggenerated
     */
    private String goodsColorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.goods_thumb
     *
     * @mbggenerated
     */
    private String goodsThumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.send_number
     *
     * @mbggenerated
     */
    private Short sendNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.parent_sn
     *
     * @mbggenerated
     */
    private String parentSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.merge_from
     *
     * @mbggenerated
     */
    private String mergeFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.exchange_from
     *
     * @mbggenerated
     */
    private String exchangeFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.promotion_desc
     *
     * @mbggenerated
     */
    private String promotionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.rank_points
     *
     * @mbggenerated
     */
    private BigDecimal rankPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.pay_points
     *
     * @mbggenerated
     */
    private BigDecimal payPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.use_card
     *
     * @mbggenerated
     */
    private String useCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.share_bonus
     *
     * @mbggenerated
     */
    private BigDecimal shareBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.share_surplus
     *
     * @mbggenerated
     */
    private BigDecimal shareSurplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.made_flag
     *
     * @mbggenerated
     */
    private Byte madeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.charge_back_count
     *
     * @mbggenerated
     */
    private Integer chargeBackCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.containerId
     *
     * @mbggenerated
     */
    private String containerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.sellerUser
     *
     * @mbggenerated
     */
    private String selleruser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.is_del
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.promotion_id
     *
     * @mbggenerated
     */
    private String promotionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.c2m_item
     *
     * @mbggenerated
     */
    private String c2mItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.protect_falg
     *
     * @mbggenerated
     */
    private Integer protectFalg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.supplier_code
     *
     * @mbggenerated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.goods_sn
     *
     * @mbggenerated
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.sales_mode
     *
     * @mbggenerated
     */
    private Byte salesMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods_temp.channel_send_number
     *
     * @mbggenerated
     */
    private Short channelSendNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.id
     *
     * @return the value of master_order_goods_temp.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.id
     *
     * @param id the value for master_order_goods_temp.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.depot_code
     *
     * @return the value of master_order_goods_temp.depot_code
     *
     * @mbggenerated
     */
    public String getDepotCode() {
        return depotCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.depot_code
     *
     * @param depotCode the value for master_order_goods_temp.depot_code
     *
     * @mbggenerated
     */
    public void setDepotCode(String depotCode) {
        this.depotCode = depotCode == null ? null : depotCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.master_order_sn
     *
     * @return the value of master_order_goods_temp.master_order_sn
     *
     * @mbggenerated
     */
    public String getMasterOrderSn() {
        return masterOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.master_order_sn
     *
     * @param masterOrderSn the value for master_order_goods_temp.master_order_sn
     *
     * @mbggenerated
     */
    public void setMasterOrderSn(String masterOrderSn) {
        this.masterOrderSn = masterOrderSn == null ? null : masterOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.order_sn
     *
     * @return the value of master_order_goods_temp.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.order_sn
     *
     * @param orderSn the value for master_order_goods_temp.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.goods_name
     *
     * @return the value of master_order_goods_temp.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.goods_name
     *
     * @param goodsName the value for master_order_goods_temp.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.custom_code
     *
     * @return the value of master_order_goods_temp.custom_code
     *
     * @mbggenerated
     */
    public String getCustomCode() {
        return customCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.custom_code
     *
     * @param customCode the value for master_order_goods_temp.custom_code
     *
     * @mbggenerated
     */
    public void setCustomCode(String customCode) {
        this.customCode = customCode == null ? null : customCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.extension_code
     *
     * @return the value of master_order_goods_temp.extension_code
     *
     * @mbggenerated
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.extension_code
     *
     * @param extensionCode the value for master_order_goods_temp.extension_code
     *
     * @mbggenerated
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.extension_id
     *
     * @return the value of master_order_goods_temp.extension_id
     *
     * @mbggenerated
     */
    public String getExtensionId() {
        return extensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.extension_id
     *
     * @param extensionId the value for master_order_goods_temp.extension_id
     *
     * @mbggenerated
     */
    public void setExtensionId(String extensionId) {
        this.extensionId = extensionId == null ? null : extensionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.goods_number
     *
     * @return the value of master_order_goods_temp.goods_number
     *
     * @mbggenerated
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.goods_number
     *
     * @param goodsNumber the value for master_order_goods_temp.goods_number
     *
     * @mbggenerated
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.goods_price
     *
     * @return the value of master_order_goods_temp.goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.goods_price
     *
     * @param goodsPrice the value for master_order_goods_temp.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.transaction_price
     *
     * @return the value of master_order_goods_temp.transaction_price
     *
     * @mbggenerated
     */
    public BigDecimal getTransactionPrice() {
        return transactionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.transaction_price
     *
     * @param transactionPrice the value for master_order_goods_temp.transaction_price
     *
     * @mbggenerated
     */
    public void setTransactionPrice(BigDecimal transactionPrice) {
        this.transactionPrice = transactionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.settlement_price
     *
     * @return the value of master_order_goods_temp.settlement_price
     *
     * @mbggenerated
     */
    public BigDecimal getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.settlement_price
     *
     * @param settlementPrice the value for master_order_goods_temp.settlement_price
     *
     * @mbggenerated
     */
    public void setSettlementPrice(BigDecimal settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.discount
     *
     * @return the value of master_order_goods_temp.discount
     *
     * @mbggenerated
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.discount
     *
     * @param discount the value for master_order_goods_temp.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.integral_money
     *
     * @return the value of master_order_goods_temp.integral_money
     *
     * @mbggenerated
     */
    public BigDecimal getIntegralMoney() {
        return integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.integral_money
     *
     * @param integralMoney the value for master_order_goods_temp.integral_money
     *
     * @mbggenerated
     */
    public void setIntegralMoney(BigDecimal integralMoney) {
        this.integralMoney = integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.integral
     *
     * @return the value of master_order_goods_temp.integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.integral
     *
     * @param integral the value for master_order_goods_temp.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.group_name
     *
     * @return the value of master_order_goods_temp.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.group_name
     *
     * @param groupName the value for master_order_goods_temp.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.goods_size_name
     *
     * @return the value of master_order_goods_temp.goods_size_name
     *
     * @mbggenerated
     */
    public String getGoodsSizeName() {
        return goodsSizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.goods_size_name
     *
     * @param goodsSizeName the value for master_order_goods_temp.goods_size_name
     *
     * @mbggenerated
     */
    public void setGoodsSizeName(String goodsSizeName) {
        this.goodsSizeName = goodsSizeName == null ? null : goodsSizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.goods_color_name
     *
     * @return the value of master_order_goods_temp.goods_color_name
     *
     * @mbggenerated
     */
    public String getGoodsColorName() {
        return goodsColorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.goods_color_name
     *
     * @param goodsColorName the value for master_order_goods_temp.goods_color_name
     *
     * @mbggenerated
     */
    public void setGoodsColorName(String goodsColorName) {
        this.goodsColorName = goodsColorName == null ? null : goodsColorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.goods_thumb
     *
     * @return the value of master_order_goods_temp.goods_thumb
     *
     * @mbggenerated
     */
    public String getGoodsThumb() {
        return goodsThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.goods_thumb
     *
     * @param goodsThumb the value for master_order_goods_temp.goods_thumb
     *
     * @mbggenerated
     */
    public void setGoodsThumb(String goodsThumb) {
        this.goodsThumb = goodsThumb == null ? null : goodsThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.send_number
     *
     * @return the value of master_order_goods_temp.send_number
     *
     * @mbggenerated
     */
    public Short getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.send_number
     *
     * @param sendNumber the value for master_order_goods_temp.send_number
     *
     * @mbggenerated
     */
    public void setSendNumber(Short sendNumber) {
        this.sendNumber = sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.parent_sn
     *
     * @return the value of master_order_goods_temp.parent_sn
     *
     * @mbggenerated
     */
    public String getParentSn() {
        return parentSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.parent_sn
     *
     * @param parentSn the value for master_order_goods_temp.parent_sn
     *
     * @mbggenerated
     */
    public void setParentSn(String parentSn) {
        this.parentSn = parentSn == null ? null : parentSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.merge_from
     *
     * @return the value of master_order_goods_temp.merge_from
     *
     * @mbggenerated
     */
    public String getMergeFrom() {
        return mergeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.merge_from
     *
     * @param mergeFrom the value for master_order_goods_temp.merge_from
     *
     * @mbggenerated
     */
    public void setMergeFrom(String mergeFrom) {
        this.mergeFrom = mergeFrom == null ? null : mergeFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.exchange_from
     *
     * @return the value of master_order_goods_temp.exchange_from
     *
     * @mbggenerated
     */
    public String getExchangeFrom() {
        return exchangeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.exchange_from
     *
     * @param exchangeFrom the value for master_order_goods_temp.exchange_from
     *
     * @mbggenerated
     */
    public void setExchangeFrom(String exchangeFrom) {
        this.exchangeFrom = exchangeFrom == null ? null : exchangeFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.promotion_desc
     *
     * @return the value of master_order_goods_temp.promotion_desc
     *
     * @mbggenerated
     */
    public String getPromotionDesc() {
        return promotionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.promotion_desc
     *
     * @param promotionDesc the value for master_order_goods_temp.promotion_desc
     *
     * @mbggenerated
     */
    public void setPromotionDesc(String promotionDesc) {
        this.promotionDesc = promotionDesc == null ? null : promotionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.rank_points
     *
     * @return the value of master_order_goods_temp.rank_points
     *
     * @mbggenerated
     */
    public BigDecimal getRankPoints() {
        return rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.rank_points
     *
     * @param rankPoints the value for master_order_goods_temp.rank_points
     *
     * @mbggenerated
     */
    public void setRankPoints(BigDecimal rankPoints) {
        this.rankPoints = rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.pay_points
     *
     * @return the value of master_order_goods_temp.pay_points
     *
     * @mbggenerated
     */
    public BigDecimal getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.pay_points
     *
     * @param payPoints the value for master_order_goods_temp.pay_points
     *
     * @mbggenerated
     */
    public void setPayPoints(BigDecimal payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.use_card
     *
     * @return the value of master_order_goods_temp.use_card
     *
     * @mbggenerated
     */
    public String getUseCard() {
        return useCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.use_card
     *
     * @param useCard the value for master_order_goods_temp.use_card
     *
     * @mbggenerated
     */
    public void setUseCard(String useCard) {
        this.useCard = useCard == null ? null : useCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.share_bonus
     *
     * @return the value of master_order_goods_temp.share_bonus
     *
     * @mbggenerated
     */
    public BigDecimal getShareBonus() {
        return shareBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.share_bonus
     *
     * @param shareBonus the value for master_order_goods_temp.share_bonus
     *
     * @mbggenerated
     */
    public void setShareBonus(BigDecimal shareBonus) {
        this.shareBonus = shareBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.share_surplus
     *
     * @return the value of master_order_goods_temp.share_surplus
     *
     * @mbggenerated
     */
    public BigDecimal getShareSurplus() {
        return shareSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.share_surplus
     *
     * @param shareSurplus the value for master_order_goods_temp.share_surplus
     *
     * @mbggenerated
     */
    public void setShareSurplus(BigDecimal shareSurplus) {
        this.shareSurplus = shareSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.made_flag
     *
     * @return the value of master_order_goods_temp.made_flag
     *
     * @mbggenerated
     */
    public Byte getMadeFlag() {
        return madeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.made_flag
     *
     * @param madeFlag the value for master_order_goods_temp.made_flag
     *
     * @mbggenerated
     */
    public void setMadeFlag(Byte madeFlag) {
        this.madeFlag = madeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.charge_back_count
     *
     * @return the value of master_order_goods_temp.charge_back_count
     *
     * @mbggenerated
     */
    public Integer getChargeBackCount() {
        return chargeBackCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.charge_back_count
     *
     * @param chargeBackCount the value for master_order_goods_temp.charge_back_count
     *
     * @mbggenerated
     */
    public void setChargeBackCount(Integer chargeBackCount) {
        this.chargeBackCount = chargeBackCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.containerId
     *
     * @return the value of master_order_goods_temp.containerId
     *
     * @mbggenerated
     */
    public String getContainerid() {
        return containerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.containerId
     *
     * @param containerid the value for master_order_goods_temp.containerId
     *
     * @mbggenerated
     */
    public void setContainerid(String containerid) {
        this.containerid = containerid == null ? null : containerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.sellerUser
     *
     * @return the value of master_order_goods_temp.sellerUser
     *
     * @mbggenerated
     */
    public String getSelleruser() {
        return selleruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.sellerUser
     *
     * @param selleruser the value for master_order_goods_temp.sellerUser
     *
     * @mbggenerated
     */
    public void setSelleruser(String selleruser) {
        this.selleruser = selleruser == null ? null : selleruser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.is_del
     *
     * @return the value of master_order_goods_temp.is_del
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.is_del
     *
     * @param isDel the value for master_order_goods_temp.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.promotion_id
     *
     * @return the value of master_order_goods_temp.promotion_id
     *
     * @mbggenerated
     */
    public String getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.promotion_id
     *
     * @param promotionId the value for master_order_goods_temp.promotion_id
     *
     * @mbggenerated
     */
    public void setPromotionId(String promotionId) {
        this.promotionId = promotionId == null ? null : promotionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.c2m_item
     *
     * @return the value of master_order_goods_temp.c2m_item
     *
     * @mbggenerated
     */
    public String getC2mItem() {
        return c2mItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.c2m_item
     *
     * @param c2mItem the value for master_order_goods_temp.c2m_item
     *
     * @mbggenerated
     */
    public void setC2mItem(String c2mItem) {
        this.c2mItem = c2mItem == null ? null : c2mItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.protect_falg
     *
     * @return the value of master_order_goods_temp.protect_falg
     *
     * @mbggenerated
     */
    public Integer getProtectFalg() {
        return protectFalg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.protect_falg
     *
     * @param protectFalg the value for master_order_goods_temp.protect_falg
     *
     * @mbggenerated
     */
    public void setProtectFalg(Integer protectFalg) {
        this.protectFalg = protectFalg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.supplier_code
     *
     * @return the value of master_order_goods_temp.supplier_code
     *
     * @mbggenerated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.supplier_code
     *
     * @param supplierCode the value for master_order_goods_temp.supplier_code
     *
     * @mbggenerated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.market_price
     *
     * @return the value of master_order_goods_temp.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.market_price
     *
     * @param marketPrice the value for master_order_goods_temp.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.goods_sn
     *
     * @return the value of master_order_goods_temp.goods_sn
     *
     * @mbggenerated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.goods_sn
     *
     * @param goodsSn the value for master_order_goods_temp.goods_sn
     *
     * @mbggenerated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.sales_mode
     *
     * @return the value of master_order_goods_temp.sales_mode
     *
     * @mbggenerated
     */
    public Byte getSalesMode() {
        return salesMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.sales_mode
     *
     * @param salesMode the value for master_order_goods_temp.sales_mode
     *
     * @mbggenerated
     */
    public void setSalesMode(Byte salesMode) {
        this.salesMode = salesMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods_temp.channel_send_number
     *
     * @return the value of master_order_goods_temp.channel_send_number
     *
     * @mbggenerated
     */
    public Short getChannelSendNumber() {
        return channelSendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods_temp.channel_send_number
     *
     * @param channelSendNumber the value for master_order_goods_temp.channel_send_number
     *
     * @mbggenerated
     */
    public void setChannelSendNumber(Short channelSendNumber) {
        this.channelSendNumber = channelSendNumber;
    }
}