package com.work.shop.oms.bean;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 订单商品列表
 * @author QuYachu
 */
public class MasterOrderGoods implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 3345193354753638217L;
	
	public MasterOrderGoods() {
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.depot_code
     *
     * @mbggenerated
     */
    private String depotCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.master_order_sn
     *
     * @mbggenerated
     */
    private String masterOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.custom_code
     *
     * @mbggenerated
     */
    private String customCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.extension_code
     *
     * @mbggenerated
     */
    private String extensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.extension_id
     *
     * @mbggenerated
     */
    private String extensionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_number
     *
     * @mbggenerated
     */
    private Short goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.transaction_price
     *
     * @mbggenerated
     */
    private BigDecimal transactionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.settlement_price
     *
     * @mbggenerated
     */
    private BigDecimal settlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.integral_money
     *
     * @mbggenerated
     */
    private BigDecimal integralMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_size_name
     *
     * @mbggenerated
     */
    private String goodsSizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_color_name
     *
     * @mbggenerated
     */
    private String goodsColorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_thumb
     *
     * @mbggenerated
     */
    private String goodsThumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.send_number
     *
     * @mbggenerated
     */
    private Short sendNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.parent_sn
     *
     * @mbggenerated
     */
    private String parentSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.merge_from
     *
     * @mbggenerated
     */
    private String mergeFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.exchange_from
     *
     * @mbggenerated
     */
    private String exchangeFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.promotion_desc
     *
     * @mbggenerated
     */
    private String promotionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.rank_points
     *
     * @mbggenerated
     */
    private BigDecimal rankPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.pay_points
     *
     * @mbggenerated
     */
    private BigDecimal payPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.use_card
     *
     * @mbggenerated
     */
    private String useCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.share_bonus
     *
     * @mbggenerated
     */
    private BigDecimal shareBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.share_surplus
     *
     * @mbggenerated
     */
    private BigDecimal shareSurplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.made_flag
     *
     * @mbggenerated
     */
    private Byte madeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.charge_back_count
     *
     * @mbggenerated
     */
    private Integer chargeBackCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.containerId
     *
     * @mbggenerated
     */
    private String containerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.sellerUser
     *
     * @mbggenerated
     */
    private String selleruser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.is_del
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.promotion_id
     *
     * @mbggenerated
     */
    private String promotionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.c2m_item
     *
     * @mbggenerated
     */
    private String c2mItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.protect_falg
     *
     * @mbggenerated
     */
    private Integer protectFalg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.supplier_code
     *
     * @mbggenerated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_sn
     *
     * @mbggenerated
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.sales_mode
     *
     * @mbggenerated
     */
    private Byte salesMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.channel_send_number
     *
     * @mbggenerated
     */
    private Short channelSendNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.sap
     *
     * @mbggenerated
     */
    private String sap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.bv_value
     *
     * @mbggenerated
     */
    private String bvValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.expected_ship_date
     *
     * @mbggenerated
     */
    private String expectedShipDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.tax
     *
     * @mbggenerated
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.tax_rate
     *
     * @mbggenerated
     */
    private BigDecimal taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.base_bv_value
     *
     * @mbggenerated
     */
    private Integer baseBvValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.input_tax
     *
     * @mbggenerated
     */
    private BigDecimal inputTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.output_tax
     *
     * @mbggenerated
     */
    private BigDecimal outputTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.cost_price
     *
     * @mbggenerated
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.box_gauge
     *
     * @mbggenerated
     */
    private Short boxGauge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.distribution_category
     *
     * @mbggenerated
     */
    private String distributionCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.seller_custom_code
     *
     * @mbggenerated
     */
    private String sellerCustomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.seller_goods_sn
     *
     * @mbggenerated
     */
    private String sellerGoodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.min_buy_num
     *
     * @mbggenerated
     */
    private Integer minBuyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.customer_material_code
     *
     * @mbggenerated
     */
    private String customerMaterialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.buy_unit
     *
     * @mbggenerated
     */
    private String buyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.delivery_cycle
     *
     * @mbggenerated
     */
    private String deliveryCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.invoice_no
     *
     * @mbggenerated
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_order_goods.goods_prop
     *
     * @mbggenerated
     */
    private String goodsProp;

    /**
     * 供应商名称
     */
    private String supplierName;

    /**
     * 物料描述
     */
    private String customerMaterialName;

    /**
     * 采购申请编号
     */
    private String buyerNo;

    /**
     * 采购申请行号
     */
    private String buyerLineNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.id
     *
     * @return the value of master_order_goods.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.id
     *
     * @param id the value for master_order_goods.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.depot_code
     *
     * @return the value of master_order_goods.depot_code
     *
     * @mbggenerated
     */
    public String getDepotCode() {
        return depotCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.depot_code
     *
     * @param depotCode the value for master_order_goods.depot_code
     *
     * @mbggenerated
     */
    public void setDepotCode(String depotCode) {
        this.depotCode = depotCode == null ? null : depotCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.master_order_sn
     *
     * @return the value of master_order_goods.master_order_sn
     *
     * @mbggenerated
     */
    public String getMasterOrderSn() {
        return masterOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.master_order_sn
     *
     * @param masterOrderSn the value for master_order_goods.master_order_sn
     *
     * @mbggenerated
     */
    public void setMasterOrderSn(String masterOrderSn) {
        this.masterOrderSn = masterOrderSn == null ? null : masterOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.order_sn
     *
     * @return the value of master_order_goods.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.order_sn
     *
     * @param orderSn the value for master_order_goods.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_name
     *
     * @return the value of master_order_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_name
     *
     * @param goodsName the value for master_order_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.custom_code
     *
     * @return the value of master_order_goods.custom_code
     *
     * @mbggenerated
     */
    public String getCustomCode() {
        return customCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.custom_code
     *
     * @param customCode the value for master_order_goods.custom_code
     *
     * @mbggenerated
     */
    public void setCustomCode(String customCode) {
        this.customCode = customCode == null ? null : customCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.extension_code
     *
     * @return the value of master_order_goods.extension_code
     *
     * @mbggenerated
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.extension_code
     *
     * @param extensionCode the value for master_order_goods.extension_code
     *
     * @mbggenerated
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.extension_id
     *
     * @return the value of master_order_goods.extension_id
     *
     * @mbggenerated
     */
    public String getExtensionId() {
        return extensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.extension_id
     *
     * @param extensionId the value for master_order_goods.extension_id
     *
     * @mbggenerated
     */
    public void setExtensionId(String extensionId) {
        this.extensionId = extensionId == null ? null : extensionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_number
     *
     * @return the value of master_order_goods.goods_number
     *
     * @mbggenerated
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_number
     *
     * @param goodsNumber the value for master_order_goods.goods_number
     *
     * @mbggenerated
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_price
     *
     * @return the value of master_order_goods.goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_price
     *
     * @param goodsPrice the value for master_order_goods.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.transaction_price
     *
     * @return the value of master_order_goods.transaction_price
     *
     * @mbggenerated
     */
    public BigDecimal getTransactionPrice() {
        return transactionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.transaction_price
     *
     * @param transactionPrice the value for master_order_goods.transaction_price
     *
     * @mbggenerated
     */
    public void setTransactionPrice(BigDecimal transactionPrice) {
        this.transactionPrice = transactionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.settlement_price
     *
     * @return the value of master_order_goods.settlement_price
     *
     * @mbggenerated
     */
    public BigDecimal getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.settlement_price
     *
     * @param settlementPrice the value for master_order_goods.settlement_price
     *
     * @mbggenerated
     */
    public void setSettlementPrice(BigDecimal settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.discount
     *
     * @return the value of master_order_goods.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.discount
     *
     * @param discount the value for master_order_goods.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.integral_money
     *
     * @return the value of master_order_goods.integral_money
     *
     * @mbggenerated
     */
    public BigDecimal getIntegralMoney() {
        return integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.integral_money
     *
     * @param integralMoney the value for master_order_goods.integral_money
     *
     * @mbggenerated
     */
    public void setIntegralMoney(BigDecimal integralMoney) {
        this.integralMoney = integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.integral
     *
     * @return the value of master_order_goods.integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.integral
     *
     * @param integral the value for master_order_goods.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.group_name
     *
     * @return the value of master_order_goods.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.group_name
     *
     * @param groupName the value for master_order_goods.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_size_name
     *
     * @return the value of master_order_goods.goods_size_name
     *
     * @mbggenerated
     */
    public String getGoodsSizeName() {
        return goodsSizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_size_name
     *
     * @param goodsSizeName the value for master_order_goods.goods_size_name
     *
     * @mbggenerated
     */
    public void setGoodsSizeName(String goodsSizeName) {
        this.goodsSizeName = goodsSizeName == null ? null : goodsSizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_color_name
     *
     * @return the value of master_order_goods.goods_color_name
     *
     * @mbggenerated
     */
    public String getGoodsColorName() {
        return goodsColorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_color_name
     *
     * @param goodsColorName the value for master_order_goods.goods_color_name
     *
     * @mbggenerated
     */
    public void setGoodsColorName(String goodsColorName) {
        this.goodsColorName = goodsColorName == null ? null : goodsColorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_thumb
     *
     * @return the value of master_order_goods.goods_thumb
     *
     * @mbggenerated
     */
    public String getGoodsThumb() {
        return goodsThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_thumb
     *
     * @param goodsThumb the value for master_order_goods.goods_thumb
     *
     * @mbggenerated
     */
    public void setGoodsThumb(String goodsThumb) {
        this.goodsThumb = goodsThumb == null ? null : goodsThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.send_number
     *
     * @return the value of master_order_goods.send_number
     *
     * @mbggenerated
     */
    public Short getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.send_number
     *
     * @param sendNumber the value for master_order_goods.send_number
     *
     * @mbggenerated
     */
    public void setSendNumber(Short sendNumber) {
        this.sendNumber = sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.parent_sn
     *
     * @return the value of master_order_goods.parent_sn
     *
     * @mbggenerated
     */
    public String getParentSn() {
        return parentSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.parent_sn
     *
     * @param parentSn the value for master_order_goods.parent_sn
     *
     * @mbggenerated
     */
    public void setParentSn(String parentSn) {
        this.parentSn = parentSn == null ? null : parentSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.merge_from
     *
     * @return the value of master_order_goods.merge_from
     *
     * @mbggenerated
     */
    public String getMergeFrom() {
        return mergeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.merge_from
     *
     * @param mergeFrom the value for master_order_goods.merge_from
     *
     * @mbggenerated
     */
    public void setMergeFrom(String mergeFrom) {
        this.mergeFrom = mergeFrom == null ? null : mergeFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.exchange_from
     *
     * @return the value of master_order_goods.exchange_from
     *
     * @mbggenerated
     */
    public String getExchangeFrom() {
        return exchangeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.exchange_from
     *
     * @param exchangeFrom the value for master_order_goods.exchange_from
     *
     * @mbggenerated
     */
    public void setExchangeFrom(String exchangeFrom) {
        this.exchangeFrom = exchangeFrom == null ? null : exchangeFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.promotion_desc
     *
     * @return the value of master_order_goods.promotion_desc
     *
     * @mbggenerated
     */
    public String getPromotionDesc() {
        return promotionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.promotion_desc
     *
     * @param promotionDesc the value for master_order_goods.promotion_desc
     *
     * @mbggenerated
     */
    public void setPromotionDesc(String promotionDesc) {
        this.promotionDesc = promotionDesc == null ? null : promotionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.rank_points
     *
     * @return the value of master_order_goods.rank_points
     *
     * @mbggenerated
     */
    public BigDecimal getRankPoints() {
        return rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.rank_points
     *
     * @param rankPoints the value for master_order_goods.rank_points
     *
     * @mbggenerated
     */
    public void setRankPoints(BigDecimal rankPoints) {
        this.rankPoints = rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.pay_points
     *
     * @return the value of master_order_goods.pay_points
     *
     * @mbggenerated
     */
    public BigDecimal getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.pay_points
     *
     * @param payPoints the value for master_order_goods.pay_points
     *
     * @mbggenerated
     */
    public void setPayPoints(BigDecimal payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.use_card
     *
     * @return the value of master_order_goods.use_card
     *
     * @mbggenerated
     */
    public String getUseCard() {
        return useCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.use_card
     *
     * @param useCard the value for master_order_goods.use_card
     *
     * @mbggenerated
     */
    public void setUseCard(String useCard) {
        this.useCard = useCard == null ? null : useCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.share_bonus
     *
     * @return the value of master_order_goods.share_bonus
     *
     * @mbggenerated
     */
    public BigDecimal getShareBonus() {
        return shareBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.share_bonus
     *
     * @param shareBonus the value for master_order_goods.share_bonus
     *
     * @mbggenerated
     */
    public void setShareBonus(BigDecimal shareBonus) {
        this.shareBonus = shareBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.share_surplus
     *
     * @return the value of master_order_goods.share_surplus
     *
     * @mbggenerated
     */
    public BigDecimal getShareSurplus() {
        return shareSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.share_surplus
     *
     * @param shareSurplus the value for master_order_goods.share_surplus
     *
     * @mbggenerated
     */
    public void setShareSurplus(BigDecimal shareSurplus) {
        this.shareSurplus = shareSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.made_flag
     *
     * @return the value of master_order_goods.made_flag
     *
     * @mbggenerated
     */
    public Byte getMadeFlag() {
        return madeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.made_flag
     *
     * @param madeFlag the value for master_order_goods.made_flag
     *
     * @mbggenerated
     */
    public void setMadeFlag(Byte madeFlag) {
        this.madeFlag = madeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.charge_back_count
     *
     * @return the value of master_order_goods.charge_back_count
     *
     * @mbggenerated
     */
    public Integer getChargeBackCount() {
        return chargeBackCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.charge_back_count
     *
     * @param chargeBackCount the value for master_order_goods.charge_back_count
     *
     * @mbggenerated
     */
    public void setChargeBackCount(Integer chargeBackCount) {
        this.chargeBackCount = chargeBackCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.containerId
     *
     * @return the value of master_order_goods.containerId
     *
     * @mbggenerated
     */
    public String getContainerid() {
        return containerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.containerId
     *
     * @param containerid the value for master_order_goods.containerId
     *
     * @mbggenerated
     */
    public void setContainerid(String containerid) {
        this.containerid = containerid == null ? null : containerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.sellerUser
     *
     * @return the value of master_order_goods.sellerUser
     *
     * @mbggenerated
     */
    public String getSelleruser() {
        return selleruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.sellerUser
     *
     * @param selleruser the value for master_order_goods.sellerUser
     *
     * @mbggenerated
     */
    public void setSelleruser(String selleruser) {
        this.selleruser = selleruser == null ? null : selleruser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.is_del
     *
     * @return the value of master_order_goods.is_del
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.is_del
     *
     * @param isDel the value for master_order_goods.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.promotion_id
     *
     * @return the value of master_order_goods.promotion_id
     *
     * @mbggenerated
     */
    public String getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.promotion_id
     *
     * @param promotionId the value for master_order_goods.promotion_id
     *
     * @mbggenerated
     */
    public void setPromotionId(String promotionId) {
        this.promotionId = promotionId == null ? null : promotionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.c2m_item
     *
     * @return the value of master_order_goods.c2m_item
     *
     * @mbggenerated
     */
    public String getC2mItem() {
        return c2mItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.c2m_item
     *
     * @param c2mItem the value for master_order_goods.c2m_item
     *
     * @mbggenerated
     */
    public void setC2mItem(String c2mItem) {
        this.c2mItem = c2mItem == null ? null : c2mItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.protect_falg
     *
     * @return the value of master_order_goods.protect_falg
     *
     * @mbggenerated
     */
    public Integer getProtectFalg() {
        return protectFalg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.protect_falg
     *
     * @param protectFalg the value for master_order_goods.protect_falg
     *
     * @mbggenerated
     */
    public void setProtectFalg(Integer protectFalg) {
        this.protectFalg = protectFalg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.supplier_code
     *
     * @return the value of master_order_goods.supplier_code
     *
     * @mbggenerated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.supplier_code
     *
     * @param supplierCode the value for master_order_goods.supplier_code
     *
     * @mbggenerated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.market_price
     *
     * @return the value of master_order_goods.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.market_price
     *
     * @param marketPrice the value for master_order_goods.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_sn
     *
     * @return the value of master_order_goods.goods_sn
     *
     * @mbggenerated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_sn
     *
     * @param goodsSn the value for master_order_goods.goods_sn
     *
     * @mbggenerated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.sales_mode
     *
     * @return the value of master_order_goods.sales_mode
     *
     * @mbggenerated
     */
    public Byte getSalesMode() {
        return salesMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.sales_mode
     *
     * @param salesMode the value for master_order_goods.sales_mode
     *
     * @mbggenerated
     */
    public void setSalesMode(Byte salesMode) {
        this.salesMode = salesMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.channel_send_number
     *
     * @return the value of master_order_goods.channel_send_number
     *
     * @mbggenerated
     */
    public Short getChannelSendNumber() {
        return channelSendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.channel_send_number
     *
     * @param channelSendNumber the value for master_order_goods.channel_send_number
     *
     * @mbggenerated
     */
    public void setChannelSendNumber(Short channelSendNumber) {
        this.channelSendNumber = channelSendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.sap
     *
     * @return the value of master_order_goods.sap
     *
     * @mbggenerated
     */
    public String getSap() {
        return sap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.sap
     *
     * @param sap the value for master_order_goods.sap
     *
     * @mbggenerated
     */
    public void setSap(String sap) {
        this.sap = sap == null ? null : sap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.bv_value
     *
     * @return the value of master_order_goods.bv_value
     *
     * @mbggenerated
     */
    public String getBvValue() {
        return bvValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.bv_value
     *
     * @param bvValue the value for master_order_goods.bv_value
     *
     * @mbggenerated
     */
    public void setBvValue(String bvValue) {
        this.bvValue = bvValue == null ? null : bvValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.expected_ship_date
     *
     * @return the value of master_order_goods.expected_ship_date
     *
     * @mbggenerated
     */
    public String getExpectedShipDate() {
        return expectedShipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.expected_ship_date
     *
     * @param expectedShipDate the value for master_order_goods.expected_ship_date
     *
     * @mbggenerated
     */
    public void setExpectedShipDate(String expectedShipDate) {
        this.expectedShipDate = expectedShipDate == null ? null : expectedShipDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.tax
     *
     * @return the value of master_order_goods.tax
     *
     * @mbggenerated
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.tax
     *
     * @param tax the value for master_order_goods.tax
     *
     * @mbggenerated
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.tax_rate
     *
     * @return the value of master_order_goods.tax_rate
     *
     * @mbggenerated
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.tax_rate
     *
     * @param taxRate the value for master_order_goods.tax_rate
     *
     * @mbggenerated
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.base_bv_value
     *
     * @return the value of master_order_goods.base_bv_value
     *
     * @mbggenerated
     */
    public Integer getBaseBvValue() {
        return baseBvValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.base_bv_value
     *
     * @param baseBvValue the value for master_order_goods.base_bv_value
     *
     * @mbggenerated
     */
    public void setBaseBvValue(Integer baseBvValue) {
        this.baseBvValue = baseBvValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.input_tax
     *
     * @return the value of master_order_goods.input_tax
     *
     * @mbggenerated
     */
    public BigDecimal getInputTax() {
        return inputTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.input_tax
     *
     * @param inputTax the value for master_order_goods.input_tax
     *
     * @mbggenerated
     */
    public void setInputTax(BigDecimal inputTax) {
        this.inputTax = inputTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.output_tax
     *
     * @return the value of master_order_goods.output_tax
     *
     * @mbggenerated
     */
    public BigDecimal getOutputTax() {
        return outputTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.output_tax
     *
     * @param outputTax the value for master_order_goods.output_tax
     *
     * @mbggenerated
     */
    public void setOutputTax(BigDecimal outputTax) {
        this.outputTax = outputTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.cost_price
     *
     * @return the value of master_order_goods.cost_price
     *
     * @mbggenerated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.cost_price
     *
     * @param costPrice the value for master_order_goods.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.box_gauge
     *
     * @return the value of master_order_goods.box_gauge
     *
     * @mbggenerated
     */
    public Short getBoxGauge() {
        return boxGauge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.box_gauge
     *
     * @param boxGauge the value for master_order_goods.box_gauge
     *
     * @mbggenerated
     */
    public void setBoxGauge(Short boxGauge) {
        this.boxGauge = boxGauge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.distribution_category
     *
     * @return the value of master_order_goods.distribution_category
     *
     * @mbggenerated
     */
    public String getDistributionCategory() {
        return distributionCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.distribution_category
     *
     * @param distributionCategory the value for master_order_goods.distribution_category
     *
     * @mbggenerated
     */
    public void setDistributionCategory(String distributionCategory) {
        this.distributionCategory = distributionCategory == null ? null : distributionCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.seller_custom_code
     *
     * @return the value of master_order_goods.seller_custom_code
     *
     * @mbggenerated
     */
    public String getSellerCustomCode() {
        return sellerCustomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.seller_custom_code
     *
     * @param sellerCustomCode the value for master_order_goods.seller_custom_code
     *
     * @mbggenerated
     */
    public void setSellerCustomCode(String sellerCustomCode) {
        this.sellerCustomCode = sellerCustomCode == null ? null : sellerCustomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.seller_goods_sn
     *
     * @return the value of master_order_goods.seller_goods_sn
     *
     * @mbggenerated
     */
    public String getSellerGoodsSn() {
        return sellerGoodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.seller_goods_sn
     *
     * @param sellerGoodsSn the value for master_order_goods.seller_goods_sn
     *
     * @mbggenerated
     */
    public void setSellerGoodsSn(String sellerGoodsSn) {
        this.sellerGoodsSn = sellerGoodsSn == null ? null : sellerGoodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.min_buy_num
     *
     * @return the value of master_order_goods.min_buy_num
     *
     * @mbggenerated
     */
    public Integer getMinBuyNum() {
        return minBuyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.min_buy_num
     *
     * @param minBuyNum the value for master_order_goods.min_buy_num
     *
     * @mbggenerated
     */
    public void setMinBuyNum(Integer minBuyNum) {
        this.minBuyNum = minBuyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.customer_material_code
     *
     * @return the value of master_order_goods.customer_material_code
     *
     * @mbggenerated
     */
    public String getCustomerMaterialCode() {
        return customerMaterialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.customer_material_code
     *
     * @param customerMaterialCode the value for master_order_goods.customer_material_code
     *
     * @mbggenerated
     */
    public void setCustomerMaterialCode(String customerMaterialCode) {
        this.customerMaterialCode = customerMaterialCode == null ? null : customerMaterialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.buy_unit
     *
     * @return the value of master_order_goods.buy_unit
     *
     * @mbggenerated
     */
    public String getBuyUnit() {
        return buyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.buy_unit
     *
     * @param buyUnit the value for master_order_goods.buy_unit
     *
     * @mbggenerated
     */
    public void setBuyUnit(String buyUnit) {
        this.buyUnit = buyUnit == null ? null : buyUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.delivery_cycle
     *
     * @return the value of master_order_goods.delivery_cycle
     *
     * @mbggenerated
     */
    public String getDeliveryCycle() {
        return deliveryCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.delivery_cycle
     *
     * @param deliveryCycle the value for master_order_goods.delivery_cycle
     *
     * @mbggenerated
     */
    public void setDeliveryCycle(String deliveryCycle) {
        this.deliveryCycle = deliveryCycle == null ? null : deliveryCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.invoice_no
     *
     * @return the value of master_order_goods.invoice_no
     *
     * @mbggenerated
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.invoice_no
     *
     * @param invoiceNo the value for master_order_goods.invoice_no
     *
     * @mbggenerated
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_order_goods.goods_prop
     *
     * @return the value of master_order_goods.goods_prop
     *
     * @mbggenerated
     */
    public String getGoodsProp() {
        return goodsProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_order_goods.goods_prop
     *
     * @param goodsProp the value for master_order_goods.goods_prop
     *
     * @mbggenerated
     */
    public void setGoodsProp(String goodsProp) {
        this.goodsProp = goodsProp == null ? null : goodsProp.trim();
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public String getCustomerMaterialName() {
        return customerMaterialName;
    }

    public void setCustomerMaterialName(String customerMaterialName) {
        this.customerMaterialName = customerMaterialName;
    }

    public String getBuyerNo() {
        return buyerNo;
    }

    public void setBuyerNo(String buyerNo) {
        this.buyerNo = buyerNo;
    }

    public String getBuyerLineNo() {
        return buyerLineNo;
    }

    public void setBuyerLineNo(String buyerLineNo) {
        this.buyerLineNo = buyerLineNo;
    }
}
