package com.work.shop.oms.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ErpStatusInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public ErpStatusInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**  
         * limit 
         * 
         */ 
        public Criteria limit(int offset, int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit",offset,len,"null");
            return (Criteria) this;
        }

        /**  
         * top 
         * 
         */ 
        public Criteria limit(int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit", 0, len, "null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andErpIdIsNull() {
            addCriterion("erp_ID is null");
            return (Criteria) this;
        }

        public Criteria andErpIdIsNotNull() {
            addCriterion("erp_ID is not null");
            return (Criteria) this;
        }

        public Criteria andErpIdEqualTo(String value) {
            addCriterion("erp_ID =", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdNotEqualTo(String value) {
            addCriterion("erp_ID <>", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdGreaterThan(String value) {
            addCriterion("erp_ID >", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdGreaterThanOrEqualTo(String value) {
            addCriterion("erp_ID >=", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdLessThan(String value) {
            addCriterion("erp_ID <", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdLessThanOrEqualTo(String value) {
            addCriterion("erp_ID <=", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdLike(String value) {
            addCriterion("erp_ID like", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdNotLike(String value) {
            addCriterion("erp_ID not like", value, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdIn(List<String> values) {
            addCriterion("erp_ID in", values, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdNotIn(List<String> values) {
            addCriterion("erp_ID not in", values, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdBetween(String value1, String value2) {
            addCriterion("erp_ID between", value1, value2, "erpId");
            return (Criteria) this;
        }

        public Criteria andErpIdNotBetween(String value1, String value2) {
            addCriterion("erp_ID not between", value1, value2, "erpId");
            return (Criteria) this;
        }

        public Criteria andDocTypeIsNull() {
            addCriterion("doc_type is null");
            return (Criteria) this;
        }

        public Criteria andDocTypeIsNotNull() {
            addCriterion("doc_type is not null");
            return (Criteria) this;
        }

        public Criteria andDocTypeEqualTo(String value) {
            addCriterion("doc_type =", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotEqualTo(String value) {
            addCriterion("doc_type <>", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeGreaterThan(String value) {
            addCriterion("doc_type >", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeGreaterThanOrEqualTo(String value) {
            addCriterion("doc_type >=", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLessThan(String value) {
            addCriterion("doc_type <", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLessThanOrEqualTo(String value) {
            addCriterion("doc_type <=", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLike(String value) {
            addCriterion("doc_type like", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotLike(String value) {
            addCriterion("doc_type not like", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeIn(List<String> values) {
            addCriterion("doc_type in", values, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotIn(List<String> values) {
            addCriterion("doc_type not in", values, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeBetween(String value1, String value2) {
            addCriterion("doc_type between", value1, value2, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotBetween(String value1, String value2) {
            addCriterion("doc_type not between", value1, value2, "docType");
            return (Criteria) this;
        }

        public Criteria andDocIdIsNull() {
            addCriterion("doc_ID is null");
            return (Criteria) this;
        }

        public Criteria andDocIdIsNotNull() {
            addCriterion("doc_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDocIdEqualTo(String value) {
            addCriterion("doc_ID =", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotEqualTo(String value) {
            addCriterion("doc_ID <>", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThan(String value) {
            addCriterion("doc_ID >", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThanOrEqualTo(String value) {
            addCriterion("doc_ID >=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThan(String value) {
            addCriterion("doc_ID <", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThanOrEqualTo(String value) {
            addCriterion("doc_ID <=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLike(String value) {
            addCriterion("doc_ID like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotLike(String value) {
            addCriterion("doc_ID not like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdIn(List<String> values) {
            addCriterion("doc_ID in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotIn(List<String> values) {
            addCriterion("doc_ID not in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdBetween(String value1, String value2) {
            addCriterion("doc_ID between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotBetween(String value1, String value2) {
            addCriterion("doc_ID not between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateIsNull() {
            addCriterion("doc_org_sate is null");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateIsNotNull() {
            addCriterion("doc_org_sate is not null");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateEqualTo(String value) {
            addCriterion("doc_org_sate =", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateNotEqualTo(String value) {
            addCriterion("doc_org_sate <>", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateGreaterThan(String value) {
            addCriterion("doc_org_sate >", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateGreaterThanOrEqualTo(String value) {
            addCriterion("doc_org_sate >=", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateLessThan(String value) {
            addCriterion("doc_org_sate <", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateLessThanOrEqualTo(String value) {
            addCriterion("doc_org_sate <=", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateLike(String value) {
            addCriterion("doc_org_sate like", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateNotLike(String value) {
            addCriterion("doc_org_sate not like", value, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateIn(List<String> values) {
            addCriterion("doc_org_sate in", values, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateNotIn(List<String> values) {
            addCriterion("doc_org_sate not in", values, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateBetween(String value1, String value2) {
            addCriterion("doc_org_sate between", value1, value2, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andDocOrgSateNotBetween(String value1, String value2) {
            addCriterion("doc_org_sate not between", value1, value2, "docOrgSate");
            return (Criteria) this;
        }

        public Criteria andOpStateIsNull() {
            addCriterion("op_state is null");
            return (Criteria) this;
        }

        public Criteria andOpStateIsNotNull() {
            addCriterion("op_state is not null");
            return (Criteria) this;
        }

        public Criteria andOpStateEqualTo(String value) {
            addCriterion("op_state =", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateNotEqualTo(String value) {
            addCriterion("op_state <>", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateGreaterThan(String value) {
            addCriterion("op_state >", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateGreaterThanOrEqualTo(String value) {
            addCriterion("op_state >=", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateLessThan(String value) {
            addCriterion("op_state <", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateLessThanOrEqualTo(String value) {
            addCriterion("op_state <=", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateLike(String value) {
            addCriterion("op_state like", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateNotLike(String value) {
            addCriterion("op_state not like", value, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateIn(List<String> values) {
            addCriterion("op_state in", values, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateNotIn(List<String> values) {
            addCriterion("op_state not in", values, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateBetween(String value1, String value2) {
            addCriterion("op_state between", value1, value2, "opState");
            return (Criteria) this;
        }

        public Criteria andOpStateNotBetween(String value1, String value2) {
            addCriterion("op_state not between", value1, value2, "opState");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeIsNull() {
            addCriterion("op_user_code is null");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeIsNotNull() {
            addCriterion("op_user_code is not null");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeEqualTo(String value) {
            addCriterion("op_user_code =", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeNotEqualTo(String value) {
            addCriterion("op_user_code <>", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeGreaterThan(String value) {
            addCriterion("op_user_code >", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("op_user_code >=", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeLessThan(String value) {
            addCriterion("op_user_code <", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeLessThanOrEqualTo(String value) {
            addCriterion("op_user_code <=", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeLike(String value) {
            addCriterion("op_user_code like", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeNotLike(String value) {
            addCriterion("op_user_code not like", value, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeIn(List<String> values) {
            addCriterion("op_user_code in", values, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeNotIn(List<String> values) {
            addCriterion("op_user_code not in", values, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeBetween(String value1, String value2) {
            addCriterion("op_user_code between", value1, value2, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserCodeNotBetween(String value1, String value2) {
            addCriterion("op_user_code not between", value1, value2, "opUserCode");
            return (Criteria) this;
        }

        public Criteria andOpUserNameIsNull() {
            addCriterion("op_user_name is null");
            return (Criteria) this;
        }

        public Criteria andOpUserNameIsNotNull() {
            addCriterion("op_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andOpUserNameEqualTo(String value) {
            addCriterion("op_user_name =", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameNotEqualTo(String value) {
            addCriterion("op_user_name <>", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameGreaterThan(String value) {
            addCriterion("op_user_name >", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("op_user_name >=", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameLessThan(String value) {
            addCriterion("op_user_name <", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameLessThanOrEqualTo(String value) {
            addCriterion("op_user_name <=", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameLike(String value) {
            addCriterion("op_user_name like", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameNotLike(String value) {
            addCriterion("op_user_name not like", value, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameIn(List<String> values) {
            addCriterion("op_user_name in", values, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameNotIn(List<String> values) {
            addCriterion("op_user_name not in", values, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameBetween(String value1, String value2) {
            addCriterion("op_user_name between", value1, value2, "opUserName");
            return (Criteria) this;
        }

        public Criteria andOpUserNameNotBetween(String value1, String value2) {
            addCriterion("op_user_name not between", value1, value2, "opUserName");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeIsNull() {
            addCriterion("os_order_code is null");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeIsNotNull() {
            addCriterion("os_order_code is not null");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeEqualTo(String value) {
            addCriterion("os_order_code =", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeNotEqualTo(String value) {
            addCriterion("os_order_code <>", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeGreaterThan(String value) {
            addCriterion("os_order_code >", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("os_order_code >=", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeLessThan(String value) {
            addCriterion("os_order_code <", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("os_order_code <=", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeLike(String value) {
            addCriterion("os_order_code like", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeNotLike(String value) {
            addCriterion("os_order_code not like", value, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeIn(List<String> values) {
            addCriterion("os_order_code in", values, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeNotIn(List<String> values) {
            addCriterion("os_order_code not in", values, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeBetween(String value1, String value2) {
            addCriterion("os_order_code between", value1, value2, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOsOrderCodeNotBetween(String value1, String value2) {
            addCriterion("os_order_code not between", value1, value2, "osOrderCode");
            return (Criteria) this;
        }

        public Criteria andOpDateIsNull() {
            addCriterion("op_date is null");
            return (Criteria) this;
        }

        public Criteria andOpDateIsNotNull() {
            addCriterion("op_date is not null");
            return (Criteria) this;
        }

        public Criteria andOpDateEqualTo(Date value) {
            addCriterion("op_date =", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotEqualTo(Date value) {
            addCriterion("op_date <>", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateGreaterThan(Date value) {
            addCriterion("op_date >", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("op_date >=", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateLessThan(Date value) {
            addCriterion("op_date <", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateLessThanOrEqualTo(Date value) {
            addCriterion("op_date <=", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateIn(List<Date> values) {
            addCriterion("op_date in", values, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotIn(List<Date> values) {
            addCriterion("op_date not in", values, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateBetween(Date value1, Date value2) {
            addCriterion("op_date between", value1, value2, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotBetween(Date value1, Date value2) {
            addCriterion("op_date not between", value1, value2, "opDate");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDepotCodeIsNull() {
            addCriterion("depot_code is null");
            return (Criteria) this;
        }

        public Criteria andDepotCodeIsNotNull() {
            addCriterion("depot_code is not null");
            return (Criteria) this;
        }

        public Criteria andDepotCodeEqualTo(String value) {
            addCriterion("depot_code =", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeNotEqualTo(String value) {
            addCriterion("depot_code <>", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeGreaterThan(String value) {
            addCriterion("depot_code >", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeGreaterThanOrEqualTo(String value) {
            addCriterion("depot_code >=", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeLessThan(String value) {
            addCriterion("depot_code <", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeLessThanOrEqualTo(String value) {
            addCriterion("depot_code <=", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeLike(String value) {
            addCriterion("depot_code like", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeNotLike(String value) {
            addCriterion("depot_code not like", value, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeIn(List<String> values) {
            addCriterion("depot_code in", values, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeNotIn(List<String> values) {
            addCriterion("depot_code not in", values, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeBetween(String value1, String value2) {
            addCriterion("depot_code between", value1, value2, "depotCode");
            return (Criteria) this;
        }

        public Criteria andDepotCodeNotBetween(String value1, String value2) {
            addCriterion("depot_code not between", value1, value2, "depotCode");
            return (Criteria) this;
        }

        public Criteria andFromSystemIsNull() {
            addCriterion("from_system is null");
            return (Criteria) this;
        }

        public Criteria andFromSystemIsNotNull() {
            addCriterion("from_system is not null");
            return (Criteria) this;
        }

        public Criteria andFromSystemEqualTo(String value) {
            addCriterion("from_system =", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemNotEqualTo(String value) {
            addCriterion("from_system <>", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemGreaterThan(String value) {
            addCriterion("from_system >", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemGreaterThanOrEqualTo(String value) {
            addCriterion("from_system >=", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemLessThan(String value) {
            addCriterion("from_system <", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemLessThanOrEqualTo(String value) {
            addCriterion("from_system <=", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemLike(String value) {
            addCriterion("from_system like", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemNotLike(String value) {
            addCriterion("from_system not like", value, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemIn(List<String> values) {
            addCriterion("from_system in", values, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemNotIn(List<String> values) {
            addCriterion("from_system not in", values, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemBetween(String value1, String value2) {
            addCriterion("from_system between", value1, value2, "fromSystem");
            return (Criteria) this;
        }

        public Criteria andFromSystemNotBetween(String value1, String value2) {
            addCriterion("from_system not between", value1, value2, "fromSystem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table erp_status_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table erp_status_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}