package com.work.shop.oms.bean;

public class OrderQuestionLackSkuNewKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.custom_code
     *
     * @mbggenerated
     */
    private String customCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.depot_code
     *
     * @mbggenerated
     */
    private String depotCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.extension_code
     *
     * @mbggenerated
     */
    private String extensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.extension_id
     *
     * @mbggenerated
     */
    private String extensionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.question_code
     *
     * @mbggenerated
     */
    private String questionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.custom_code
     *
     * @return the value of order_question_lack_sku_new.custom_code
     *
     * @mbggenerated
     */
    public String getCustomCode() {
        return customCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.custom_code
     *
     * @param customCode the value for order_question_lack_sku_new.custom_code
     *
     * @mbggenerated
     */
    public void setCustomCode(String customCode) {
        this.customCode = customCode == null ? null : customCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.depot_code
     *
     * @return the value of order_question_lack_sku_new.depot_code
     *
     * @mbggenerated
     */
    public String getDepotCode() {
        return depotCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.depot_code
     *
     * @param depotCode the value for order_question_lack_sku_new.depot_code
     *
     * @mbggenerated
     */
    public void setDepotCode(String depotCode) {
        this.depotCode = depotCode == null ? null : depotCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.extension_code
     *
     * @return the value of order_question_lack_sku_new.extension_code
     *
     * @mbggenerated
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.extension_code
     *
     * @param extensionCode the value for order_question_lack_sku_new.extension_code
     *
     * @mbggenerated
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.extension_id
     *
     * @return the value of order_question_lack_sku_new.extension_id
     *
     * @mbggenerated
     */
    public String getExtensionId() {
        return extensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.extension_id
     *
     * @param extensionId the value for order_question_lack_sku_new.extension_id
     *
     * @mbggenerated
     */
    public void setExtensionId(String extensionId) {
        this.extensionId = extensionId == null ? null : extensionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.order_sn
     *
     * @return the value of order_question_lack_sku_new.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.order_sn
     *
     * @param orderSn the value for order_question_lack_sku_new.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.question_code
     *
     * @return the value of order_question_lack_sku_new.question_code
     *
     * @mbggenerated
     */
    public String getQuestionCode() {
        return questionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.question_code
     *
     * @param questionCode the value for order_question_lack_sku_new.question_code
     *
     * @mbggenerated
     */
    public void setQuestionCode(String questionCode) {
        this.questionCode = questionCode == null ? null : questionCode.trim();
    }
}