package com.work.shop.oms.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExpressCompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public OrderExpressCompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**  
         * limit 
         * 
         */ 
        public Criteria limit(int offset, int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit",offset,len,"null");
            return (Criteria) this;
        }

        /**  
         * top 
         * 
         */ 
        public Criteria limit(int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit", 0, len, "null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNull() {
            addCriterion("company_code is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNotNull() {
            addCriterion("company_code is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeEqualTo(String value) {
            addCriterion("company_code =", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotEqualTo(String value) {
            addCriterion("company_code <>", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThan(String value) {
            addCriterion("company_code >", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("company_code >=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThan(String value) {
            addCriterion("company_code <", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThanOrEqualTo(String value) {
            addCriterion("company_code <=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLike(String value) {
            addCriterion("company_code like", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotLike(String value) {
            addCriterion("company_code not like", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIn(List<String> values) {
            addCriterion("company_code in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotIn(List<String> values) {
            addCriterion("company_code not in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeBetween(String value1, String value2) {
            addCriterion("company_code between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotBetween(String value1, String value2) {
            addCriterion("company_code not between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andShipSnIsNull() {
            addCriterion("ship_sn is null");
            return (Criteria) this;
        }

        public Criteria andShipSnIsNotNull() {
            addCriterion("ship_sn is not null");
            return (Criteria) this;
        }

        public Criteria andShipSnEqualTo(String value) {
            addCriterion("ship_sn =", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnNotEqualTo(String value) {
            addCriterion("ship_sn <>", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnGreaterThan(String value) {
            addCriterion("ship_sn >", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnGreaterThanOrEqualTo(String value) {
            addCriterion("ship_sn >=", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnLessThan(String value) {
            addCriterion("ship_sn <", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnLessThanOrEqualTo(String value) {
            addCriterion("ship_sn <=", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnLike(String value) {
            addCriterion("ship_sn like", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnNotLike(String value) {
            addCriterion("ship_sn not like", value, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnIn(List<String> values) {
            addCriterion("ship_sn in", values, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnNotIn(List<String> values) {
            addCriterion("ship_sn not in", values, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnBetween(String value1, String value2) {
            addCriterion("ship_sn between", value1, value2, "shipSn");
            return (Criteria) this;
        }

        public Criteria andShipSnNotBetween(String value1, String value2) {
            addCriterion("ship_sn not between", value1, value2, "shipSn");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeIsNull() {
            addCriterion("last_trace_time is null");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeIsNotNull() {
            addCriterion("last_trace_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeEqualTo(Date value) {
            addCriterion("last_trace_time =", value, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeNotEqualTo(Date value) {
            addCriterion("last_trace_time <>", value, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeGreaterThan(Date value) {
            addCriterion("last_trace_time >", value, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_trace_time >=", value, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeLessThan(Date value) {
            addCriterion("last_trace_time <", value, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_trace_time <=", value, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeIn(List<Date> values) {
            addCriterion("last_trace_time in", values, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeNotIn(List<Date> values) {
            addCriterion("last_trace_time not in", values, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeBetween(Date value1, Date value2) {
            addCriterion("last_trace_time between", value1, value2, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andLastTraceTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_trace_time not between", value1, value2, "lastTraceTime");
            return (Criteria) this;
        }

        public Criteria andTraceStatusIsNull() {
            addCriterion("trace_status is null");
            return (Criteria) this;
        }

        public Criteria andTraceStatusIsNotNull() {
            addCriterion("trace_status is not null");
            return (Criteria) this;
        }

        public Criteria andTraceStatusEqualTo(String value) {
            addCriterion("trace_status =", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusNotEqualTo(String value) {
            addCriterion("trace_status <>", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusGreaterThan(String value) {
            addCriterion("trace_status >", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusGreaterThanOrEqualTo(String value) {
            addCriterion("trace_status >=", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusLessThan(String value) {
            addCriterion("trace_status <", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusLessThanOrEqualTo(String value) {
            addCriterion("trace_status <=", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusLike(String value) {
            addCriterion("trace_status like", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusNotLike(String value) {
            addCriterion("trace_status not like", value, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusIn(List<String> values) {
            addCriterion("trace_status in", values, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusNotIn(List<String> values) {
            addCriterion("trace_status not in", values, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusBetween(String value1, String value2) {
            addCriterion("trace_status between", value1, value2, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andTraceStatusNotBetween(String value1, String value2) {
            addCriterion("trace_status not between", value1, value2, "traceStatus");
            return (Criteria) this;
        }

        public Criteria andFetchDayIsNull() {
            addCriterion("fetch_day is null");
            return (Criteria) this;
        }

        public Criteria andFetchDayIsNotNull() {
            addCriterion("fetch_day is not null");
            return (Criteria) this;
        }

        public Criteria andFetchDayEqualTo(Short value) {
            addCriterion("fetch_day =", value, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayNotEqualTo(Short value) {
            addCriterion("fetch_day <>", value, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayGreaterThan(Short value) {
            addCriterion("fetch_day >", value, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayGreaterThanOrEqualTo(Short value) {
            addCriterion("fetch_day >=", value, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayLessThan(Short value) {
            addCriterion("fetch_day <", value, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayLessThanOrEqualTo(Short value) {
            addCriterion("fetch_day <=", value, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayIn(List<Short> values) {
            addCriterion("fetch_day in", values, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayNotIn(List<Short> values) {
            addCriterion("fetch_day not in", values, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayBetween(Short value1, Short value2) {
            addCriterion("fetch_day between", value1, value2, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andFetchDayNotBetween(Short value1, Short value2) {
            addCriterion("fetch_day not between", value1, value2, "fetchDay");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteIsNull() {
            addCriterion("express_website is null");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteIsNotNull() {
            addCriterion("express_website is not null");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteEqualTo(String value) {
            addCriterion("express_website =", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteNotEqualTo(String value) {
            addCriterion("express_website <>", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteGreaterThan(String value) {
            addCriterion("express_website >", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("express_website >=", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteLessThan(String value) {
            addCriterion("express_website <", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteLessThanOrEqualTo(String value) {
            addCriterion("express_website <=", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteLike(String value) {
            addCriterion("express_website like", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteNotLike(String value) {
            addCriterion("express_website not like", value, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteIn(List<String> values) {
            addCriterion("express_website in", values, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteNotIn(List<String> values) {
            addCriterion("express_website not in", values, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteBetween(String value1, String value2) {
            addCriterion("express_website between", value1, value2, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressWebsiteNotBetween(String value1, String value2) {
            addCriterion("express_website not between", value1, value2, "expressWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteIsNull() {
            addCriterion("company_website is null");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteIsNotNull() {
            addCriterion("company_website is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteEqualTo(String value) {
            addCriterion("company_website =", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotEqualTo(String value) {
            addCriterion("company_website <>", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteGreaterThan(String value) {
            addCriterion("company_website >", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("company_website >=", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteLessThan(String value) {
            addCriterion("company_website <", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteLessThanOrEqualTo(String value) {
            addCriterion("company_website <=", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteLike(String value) {
            addCriterion("company_website like", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotLike(String value) {
            addCriterion("company_website not like", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteIn(List<String> values) {
            addCriterion("company_website in", values, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotIn(List<String> values) {
            addCriterion("company_website not in", values, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteBetween(String value1, String value2) {
            addCriterion("company_website between", value1, value2, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotBetween(String value1, String value2) {
            addCriterion("company_website not between", value1, value2, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlIsNull() {
            addCriterion("express_code_url is null");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlIsNotNull() {
            addCriterion("express_code_url is not null");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlEqualTo(String value) {
            addCriterion("express_code_url =", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlNotEqualTo(String value) {
            addCriterion("express_code_url <>", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlGreaterThan(String value) {
            addCriterion("express_code_url >", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("express_code_url >=", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlLessThan(String value) {
            addCriterion("express_code_url <", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlLessThanOrEqualTo(String value) {
            addCriterion("express_code_url <=", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlLike(String value) {
            addCriterion("express_code_url like", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlNotLike(String value) {
            addCriterion("express_code_url not like", value, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlIn(List<String> values) {
            addCriterion("express_code_url in", values, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlNotIn(List<String> values) {
            addCriterion("express_code_url not in", values, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlBetween(String value1, String value2) {
            addCriterion("express_code_url between", value1, value2, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andExpressCodeUrlNotBetween(String value1, String value2) {
            addCriterion("express_code_url not between", value1, value2, "expressCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlIsNull() {
            addCriterion("company_code_url is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlIsNotNull() {
            addCriterion("company_code_url is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlEqualTo(String value) {
            addCriterion("company_code_url =", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlNotEqualTo(String value) {
            addCriterion("company_code_url <>", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlGreaterThan(String value) {
            addCriterion("company_code_url >", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("company_code_url >=", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlLessThan(String value) {
            addCriterion("company_code_url <", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlLessThanOrEqualTo(String value) {
            addCriterion("company_code_url <=", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlLike(String value) {
            addCriterion("company_code_url like", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlNotLike(String value) {
            addCriterion("company_code_url not like", value, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlIn(List<String> values) {
            addCriterion("company_code_url in", values, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlNotIn(List<String> values) {
            addCriterion("company_code_url not in", values, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlBetween(String value1, String value2) {
            addCriterion("company_code_url between", value1, value2, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeUrlNotBetween(String value1, String value2) {
            addCriterion("company_code_url not between", value1, value2, "companyCodeUrl");
            return (Criteria) this;
        }

        public Criteria andPostRefererIsNull() {
            addCriterion("post_referer is null");
            return (Criteria) this;
        }

        public Criteria andPostRefererIsNotNull() {
            addCriterion("post_referer is not null");
            return (Criteria) this;
        }

        public Criteria andPostRefererEqualTo(String value) {
            addCriterion("post_referer =", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererNotEqualTo(String value) {
            addCriterion("post_referer <>", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererGreaterThan(String value) {
            addCriterion("post_referer >", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererGreaterThanOrEqualTo(String value) {
            addCriterion("post_referer >=", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererLessThan(String value) {
            addCriterion("post_referer <", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererLessThanOrEqualTo(String value) {
            addCriterion("post_referer <=", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererLike(String value) {
            addCriterion("post_referer like", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererNotLike(String value) {
            addCriterion("post_referer not like", value, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererIn(List<String> values) {
            addCriterion("post_referer in", values, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererNotIn(List<String> values) {
            addCriterion("post_referer not in", values, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererBetween(String value1, String value2) {
            addCriterion("post_referer between", value1, value2, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostRefererNotBetween(String value1, String value2) {
            addCriterion("post_referer not between", value1, value2, "postReferer");
            return (Criteria) this;
        }

        public Criteria andPostHostIsNull() {
            addCriterion("post_host is null");
            return (Criteria) this;
        }

        public Criteria andPostHostIsNotNull() {
            addCriterion("post_host is not null");
            return (Criteria) this;
        }

        public Criteria andPostHostEqualTo(String value) {
            addCriterion("post_host =", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostNotEqualTo(String value) {
            addCriterion("post_host <>", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostGreaterThan(String value) {
            addCriterion("post_host >", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostGreaterThanOrEqualTo(String value) {
            addCriterion("post_host >=", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostLessThan(String value) {
            addCriterion("post_host <", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostLessThanOrEqualTo(String value) {
            addCriterion("post_host <=", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostLike(String value) {
            addCriterion("post_host like", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostNotLike(String value) {
            addCriterion("post_host not like", value, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostIn(List<String> values) {
            addCriterion("post_host in", values, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostNotIn(List<String> values) {
            addCriterion("post_host not in", values, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostBetween(String value1, String value2) {
            addCriterion("post_host between", value1, value2, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostHostNotBetween(String value1, String value2) {
            addCriterion("post_host not between", value1, value2, "postHost");
            return (Criteria) this;
        }

        public Criteria andPostParamIsNull() {
            addCriterion("post_param is null");
            return (Criteria) this;
        }

        public Criteria andPostParamIsNotNull() {
            addCriterion("post_param is not null");
            return (Criteria) this;
        }

        public Criteria andPostParamEqualTo(String value) {
            addCriterion("post_param =", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamNotEqualTo(String value) {
            addCriterion("post_param <>", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamGreaterThan(String value) {
            addCriterion("post_param >", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamGreaterThanOrEqualTo(String value) {
            addCriterion("post_param >=", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamLessThan(String value) {
            addCriterion("post_param <", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamLessThanOrEqualTo(String value) {
            addCriterion("post_param <=", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamLike(String value) {
            addCriterion("post_param like", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamNotLike(String value) {
            addCriterion("post_param not like", value, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamIn(List<String> values) {
            addCriterion("post_param in", values, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamNotIn(List<String> values) {
            addCriterion("post_param not in", values, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamBetween(String value1, String value2) {
            addCriterion("post_param between", value1, value2, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostParamNotBetween(String value1, String value2) {
            addCriterion("post_param not between", value1, value2, "postParam");
            return (Criteria) this;
        }

        public Criteria andPostUrlIsNull() {
            addCriterion("post_url is null");
            return (Criteria) this;
        }

        public Criteria andPostUrlIsNotNull() {
            addCriterion("post_url is not null");
            return (Criteria) this;
        }

        public Criteria andPostUrlEqualTo(String value) {
            addCriterion("post_url =", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlNotEqualTo(String value) {
            addCriterion("post_url <>", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlGreaterThan(String value) {
            addCriterion("post_url >", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlGreaterThanOrEqualTo(String value) {
            addCriterion("post_url >=", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlLessThan(String value) {
            addCriterion("post_url <", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlLessThanOrEqualTo(String value) {
            addCriterion("post_url <=", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlLike(String value) {
            addCriterion("post_url like", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlNotLike(String value) {
            addCriterion("post_url not like", value, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlIn(List<String> values) {
            addCriterion("post_url in", values, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlNotIn(List<String> values) {
            addCriterion("post_url not in", values, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlBetween(String value1, String value2) {
            addCriterion("post_url between", value1, value2, "postUrl");
            return (Criteria) this;
        }

        public Criteria andPostUrlNotBetween(String value1, String value2) {
            addCriterion("post_url not between", value1, value2, "postUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyApiIsNull() {
            addCriterion("company_api is null");
            return (Criteria) this;
        }

        public Criteria andCompanyApiIsNotNull() {
            addCriterion("company_api is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyApiEqualTo(String value) {
            addCriterion("company_api =", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiNotEqualTo(String value) {
            addCriterion("company_api <>", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiGreaterThan(String value) {
            addCriterion("company_api >", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiGreaterThanOrEqualTo(String value) {
            addCriterion("company_api >=", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiLessThan(String value) {
            addCriterion("company_api <", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiLessThanOrEqualTo(String value) {
            addCriterion("company_api <=", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiLike(String value) {
            addCriterion("company_api like", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiNotLike(String value) {
            addCriterion("company_api not like", value, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiIn(List<String> values) {
            addCriterion("company_api in", values, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiNotIn(List<String> values) {
            addCriterion("company_api not in", values, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiBetween(String value1, String value2) {
            addCriterion("company_api between", value1, value2, "companyApi");
            return (Criteria) this;
        }

        public Criteria andCompanyApiNotBetween(String value1, String value2) {
            addCriterion("company_api not between", value1, value2, "companyApi");
            return (Criteria) this;
        }

        public Criteria andSelectTypeIsNull() {
            addCriterion("select_type is null");
            return (Criteria) this;
        }

        public Criteria andSelectTypeIsNotNull() {
            addCriterion("select_type is not null");
            return (Criteria) this;
        }

        public Criteria andSelectTypeEqualTo(Short value) {
            addCriterion("select_type =", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeNotEqualTo(Short value) {
            addCriterion("select_type <>", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeGreaterThan(Short value) {
            addCriterion("select_type >", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("select_type >=", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeLessThan(Short value) {
            addCriterion("select_type <", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeLessThanOrEqualTo(Short value) {
            addCriterion("select_type <=", value, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeIn(List<Short> values) {
            addCriterion("select_type in", values, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeNotIn(List<Short> values) {
            addCriterion("select_type not in", values, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeBetween(Short value1, Short value2) {
            addCriterion("select_type between", value1, value2, "selectType");
            return (Criteria) this;
        }

        public Criteria andSelectTypeNotBetween(Short value1, Short value2) {
            addCriterion("select_type not between", value1, value2, "selectType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNull() {
            addCriterion("code_type is null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNotNull() {
            addCriterion("code_type is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeEqualTo(Short value) {
            addCriterion("code_type =", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotEqualTo(Short value) {
            addCriterion("code_type <>", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThan(Short value) {
            addCriterion("code_type >", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("code_type >=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThan(Short value) {
            addCriterion("code_type <", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThanOrEqualTo(Short value) {
            addCriterion("code_type <=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIn(List<Short> values) {
            addCriterion("code_type in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotIn(List<Short> values) {
            addCriterion("code_type not in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeBetween(Short value1, Short value2) {
            addCriterion("code_type between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotBetween(Short value1, Short value2) {
            addCriterion("code_type not between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexIsNull() {
            addCriterion("crawl_index is null");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexIsNotNull() {
            addCriterion("crawl_index is not null");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexEqualTo(String value) {
            addCriterion("crawl_index =", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexNotEqualTo(String value) {
            addCriterion("crawl_index <>", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexGreaterThan(String value) {
            addCriterion("crawl_index >", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexGreaterThanOrEqualTo(String value) {
            addCriterion("crawl_index >=", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexLessThan(String value) {
            addCriterion("crawl_index <", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexLessThanOrEqualTo(String value) {
            addCriterion("crawl_index <=", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexLike(String value) {
            addCriterion("crawl_index like", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexNotLike(String value) {
            addCriterion("crawl_index not like", value, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexIn(List<String> values) {
            addCriterion("crawl_index in", values, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexNotIn(List<String> values) {
            addCriterion("crawl_index not in", values, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexBetween(String value1, String value2) {
            addCriterion("crawl_index between", value1, value2, "crawlIndex");
            return (Criteria) this;
        }

        public Criteria andCrawlIndexNotBetween(String value1, String value2) {
            addCriterion("crawl_index not between", value1, value2, "crawlIndex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_express_company
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_express_company
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}