package com.work.shop.oms.bean;

import java.util.Date;

public class order_rider_distribute_log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.log_id
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.master_order_sn
     *
     * @mbggenerated
     */
    private String masterOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.order_out_sn
     *
     * @mbggenerated
     */
    private String orderOutSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.channel_code
     *
     * @mbggenerated
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.shop_code
     *
     * @mbggenerated
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.tms_code
     *
     * @mbggenerated
     */
    private String tmsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.tms_name
     *
     * @mbggenerated
     */
    private String tmsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.shop_no
     *
     * @mbggenerated
     */
    private String shopNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.client_order_sn
     *
     * @mbggenerated
     */
    private String clientOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.order_status
     *
     * @mbggenerated
     */
    private Short orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.status_msg
     *
     * @mbggenerated
     */
    private String statusMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.accept_time
     *
     * @mbggenerated
     */
    private Date acceptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.fetch_time
     *
     * @mbggenerated
     */
    private Date fetchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.finish_time
     *
     * @mbggenerated
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.cancel_time
     *
     * @mbggenerated
     */
    private Date cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.distance
     *
     * @mbggenerated
     */
    private Double distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.delivery_fee
     *
     * @mbggenerated
     */
    private Double deliveryFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.coupon_fee
     *
     * @mbggenerated
     */
    private Double couponFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.actual_fee
     *
     * @mbggenerated
     */
    private Double actualFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rider_distribute_log.distribute_msg
     *
     * @mbggenerated
     */
    private String distributeMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.log_id
     *
     * @return the value of order_rider_distribute_log.log_id
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.log_id
     *
     * @param logId the value for order_rider_distribute_log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.master_order_sn
     *
     * @return the value of order_rider_distribute_log.master_order_sn
     *
     * @mbggenerated
     */
    public String getMasterOrderSn() {
        return masterOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.master_order_sn
     *
     * @param masterOrderSn the value for order_rider_distribute_log.master_order_sn
     *
     * @mbggenerated
     */
    public void setMasterOrderSn(String masterOrderSn) {
        this.masterOrderSn = masterOrderSn == null ? null : masterOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.order_out_sn
     *
     * @return the value of order_rider_distribute_log.order_out_sn
     *
     * @mbggenerated
     */
    public String getOrderOutSn() {
        return orderOutSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.order_out_sn
     *
     * @param orderOutSn the value for order_rider_distribute_log.order_out_sn
     *
     * @mbggenerated
     */
    public void setOrderOutSn(String orderOutSn) {
        this.orderOutSn = orderOutSn == null ? null : orderOutSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.channel_code
     *
     * @return the value of order_rider_distribute_log.channel_code
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.channel_code
     *
     * @param channelCode the value for order_rider_distribute_log.channel_code
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.shop_code
     *
     * @return the value of order_rider_distribute_log.shop_code
     *
     * @mbggenerated
     */
    public String getShopCode() {
        return shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.shop_code
     *
     * @param shopCode the value for order_rider_distribute_log.shop_code
     *
     * @mbggenerated
     */
    public void setShopCode(String shopCode) {
        this.shopCode = shopCode == null ? null : shopCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.tms_code
     *
     * @return the value of order_rider_distribute_log.tms_code
     *
     * @mbggenerated
     */
    public String getTmsCode() {
        return tmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.tms_code
     *
     * @param tmsCode the value for order_rider_distribute_log.tms_code
     *
     * @mbggenerated
     */
    public void setTmsCode(String tmsCode) {
        this.tmsCode = tmsCode == null ? null : tmsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.tms_name
     *
     * @return the value of order_rider_distribute_log.tms_name
     *
     * @mbggenerated
     */
    public String getTmsName() {
        return tmsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.tms_name
     *
     * @param tmsName the value for order_rider_distribute_log.tms_name
     *
     * @mbggenerated
     */
    public void setTmsName(String tmsName) {
        this.tmsName = tmsName == null ? null : tmsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.shop_no
     *
     * @return the value of order_rider_distribute_log.shop_no
     *
     * @mbggenerated
     */
    public String getShopNo() {
        return shopNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.shop_no
     *
     * @param shopNo the value for order_rider_distribute_log.shop_no
     *
     * @mbggenerated
     */
    public void setShopNo(String shopNo) {
        this.shopNo = shopNo == null ? null : shopNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.client_order_sn
     *
     * @return the value of order_rider_distribute_log.client_order_sn
     *
     * @mbggenerated
     */
    public String getClientOrderSn() {
        return clientOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.client_order_sn
     *
     * @param clientOrderSn the value for order_rider_distribute_log.client_order_sn
     *
     * @mbggenerated
     */
    public void setClientOrderSn(String clientOrderSn) {
        this.clientOrderSn = clientOrderSn == null ? null : clientOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.order_status
     *
     * @return the value of order_rider_distribute_log.order_status
     *
     * @mbggenerated
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.order_status
     *
     * @param orderStatus the value for order_rider_distribute_log.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.status_msg
     *
     * @return the value of order_rider_distribute_log.status_msg
     *
     * @mbggenerated
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.status_msg
     *
     * @param statusMsg the value for order_rider_distribute_log.status_msg
     *
     * @mbggenerated
     */
    public void setStatusMsg(String statusMsg) {
        this.statusMsg = statusMsg == null ? null : statusMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.add_time
     *
     * @return the value of order_rider_distribute_log.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.add_time
     *
     * @param addTime the value for order_rider_distribute_log.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.create_time
     *
     * @return the value of order_rider_distribute_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.create_time
     *
     * @param createTime the value for order_rider_distribute_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.accept_time
     *
     * @return the value of order_rider_distribute_log.accept_time
     *
     * @mbggenerated
     */
    public Date getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.accept_time
     *
     * @param acceptTime the value for order_rider_distribute_log.accept_time
     *
     * @mbggenerated
     */
    public void setAcceptTime(Date acceptTime) {
        this.acceptTime = acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.fetch_time
     *
     * @return the value of order_rider_distribute_log.fetch_time
     *
     * @mbggenerated
     */
    public Date getFetchTime() {
        return fetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.fetch_time
     *
     * @param fetchTime the value for order_rider_distribute_log.fetch_time
     *
     * @mbggenerated
     */
    public void setFetchTime(Date fetchTime) {
        this.fetchTime = fetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.finish_time
     *
     * @return the value of order_rider_distribute_log.finish_time
     *
     * @mbggenerated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.finish_time
     *
     * @param finishTime the value for order_rider_distribute_log.finish_time
     *
     * @mbggenerated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.cancel_time
     *
     * @return the value of order_rider_distribute_log.cancel_time
     *
     * @mbggenerated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.cancel_time
     *
     * @param cancelTime the value for order_rider_distribute_log.cancel_time
     *
     * @mbggenerated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.distance
     *
     * @return the value of order_rider_distribute_log.distance
     *
     * @mbggenerated
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.distance
     *
     * @param distance the value for order_rider_distribute_log.distance
     *
     * @mbggenerated
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.delivery_fee
     *
     * @return the value of order_rider_distribute_log.delivery_fee
     *
     * @mbggenerated
     */
    public Double getDeliveryFee() {
        return deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.delivery_fee
     *
     * @param deliveryFee the value for order_rider_distribute_log.delivery_fee
     *
     * @mbggenerated
     */
    public void setDeliveryFee(Double deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.coupon_fee
     *
     * @return the value of order_rider_distribute_log.coupon_fee
     *
     * @mbggenerated
     */
    public Double getCouponFee() {
        return couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.coupon_fee
     *
     * @param couponFee the value for order_rider_distribute_log.coupon_fee
     *
     * @mbggenerated
     */
    public void setCouponFee(Double couponFee) {
        this.couponFee = couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.actual_fee
     *
     * @return the value of order_rider_distribute_log.actual_fee
     *
     * @mbggenerated
     */
    public Double getActualFee() {
        return actualFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.actual_fee
     *
     * @param actualFee the value for order_rider_distribute_log.actual_fee
     *
     * @mbggenerated
     */
    public void setActualFee(Double actualFee) {
        this.actualFee = actualFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rider_distribute_log.distribute_msg
     *
     * @return the value of order_rider_distribute_log.distribute_msg
     *
     * @mbggenerated
     */
    public String getDistributeMsg() {
        return distributeMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rider_distribute_log.distribute_msg
     *
     * @param distributeMsg the value for order_rider_distribute_log.distribute_msg
     *
     * @mbggenerated
     */
    public void setDistributeMsg(String distributeMsg) {
        this.distributeMsg = distributeMsg == null ? null : distributeMsg.trim();
    }
}