package com.work.shop.oms.bean;

public class OrderQuestionLackSkuNew extends OrderQuestionLackSkuNewKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.lack_num
     *
     * @mbggenerated
     */
    private Short lackNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.delivery_sn
     *
     * @mbggenerated
     */
    private String deliverySn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_question_lack_sku_new.lack_reason
     *
     * @mbggenerated
     */
    private String lackReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.lack_num
     *
     * @return the value of order_question_lack_sku_new.lack_num
     *
     * @mbggenerated
     */
    public Short getLackNum() {
        return lackNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.lack_num
     *
     * @param lackNum the value for order_question_lack_sku_new.lack_num
     *
     * @mbggenerated
     */
    public void setLackNum(Short lackNum) {
        this.lackNum = lackNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.delivery_sn
     *
     * @return the value of order_question_lack_sku_new.delivery_sn
     *
     * @mbggenerated
     */
    public String getDeliverySn() {
        return deliverySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.delivery_sn
     *
     * @param deliverySn the value for order_question_lack_sku_new.delivery_sn
     *
     * @mbggenerated
     */
    public void setDeliverySn(String deliverySn) {
        this.deliverySn = deliverySn == null ? null : deliverySn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_question_lack_sku_new.lack_reason
     *
     * @return the value of order_question_lack_sku_new.lack_reason
     *
     * @mbggenerated
     */
    public String getLackReason() {
        return lackReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_question_lack_sku_new.lack_reason
     *
     * @param lackReason the value for order_question_lack_sku_new.lack_reason
     *
     * @mbggenerated
     */
    public void setLackReason(String lackReason) {
        this.lackReason = lackReason == null ? null : lackReason.trim();
    }
}