package com.work.shop.oms.bean;

public class ProductGoodsWithBLOBs extends ProductGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_goods.goods_desc
     *
     * @mbggenerated
     */
    private String goodsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_goods.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_goods.sale_point
     *
     * @mbggenerated
     */
    private String salePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_goods.size_table
     *
     * @mbggenerated
     */
    private String sizeTable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_goods.goods_desc
     *
     * @return the value of product_goods.goods_desc
     *
     * @mbggenerated
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_goods.goods_desc
     *
     * @param goodsDesc the value for product_goods.goods_desc
     *
     * @mbggenerated
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_goods.answer
     *
     * @return the value of product_goods.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_goods.answer
     *
     * @param answer the value for product_goods.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_goods.sale_point
     *
     * @return the value of product_goods.sale_point
     *
     * @mbggenerated
     */
    public String getSalePoint() {
        return salePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_goods.sale_point
     *
     * @param salePoint the value for product_goods.sale_point
     *
     * @mbggenerated
     */
    public void setSalePoint(String salePoint) {
        this.salePoint = salePoint == null ? null : salePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_goods.size_table
     *
     * @return the value of product_goods.size_table
     *
     * @mbggenerated
     */
    public String getSizeTable() {
        return sizeTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_goods.size_table
     *
     * @param sizeTable the value for product_goods.size_table
     *
     * @mbggenerated
     */
    public void setSizeTable(String sizeTable) {
        this.sizeTable = sizeTable == null ? null : sizeTable.trim();
    }
}