package com.work.shop.oms.bean;

import java.io.Serializable;

public class SiteInfo implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7955235652187544986L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.site_code
     *
     * @mbggenerated
     */
    private String siteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.site_status
     *
     * @mbggenerated
     */
    private Short siteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.backup
     *
     * @mbggenerated
     */
    private String backup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.site_type
     *
     * @mbggenerated
     */
    private Short siteType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.id
     *
     * @return the value of site_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.id
     *
     * @param id the value for site_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.site_code
     *
     * @return the value of site_info.site_code
     *
     * @mbggenerated
     */
    public String getSiteCode() {
        return siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.site_code
     *
     * @param siteCode the value for site_info.site_code
     *
     * @mbggenerated
     */
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode == null ? null : siteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.site_name
     *
     * @return the value of site_info.site_name
     *
     * @mbggenerated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.site_name
     *
     * @param siteName the value for site_info.site_name
     *
     * @mbggenerated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.site_status
     *
     * @return the value of site_info.site_status
     *
     * @mbggenerated
     */
    public Short getSiteStatus() {
        return siteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.site_status
     *
     * @param siteStatus the value for site_info.site_status
     *
     * @mbggenerated
     */
    public void setSiteStatus(Short siteStatus) {
        this.siteStatus = siteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.backup
     *
     * @return the value of site_info.backup
     *
     * @mbggenerated
     */
    public String getBackup() {
        return backup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.backup
     *
     * @param backup the value for site_info.backup
     *
     * @mbggenerated
     */
    public void setBackup(String backup) {
        this.backup = backup == null ? null : backup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.site_type
     *
     * @return the value of site_info.site_type
     *
     * @mbggenerated
     */
    public Short getSiteType() {
        return siteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.site_type
     *
     * @param siteType the value for site_info.site_type
     *
     * @mbggenerated
     */
    public void setSiteType(Short siteType) {
        this.siteType = siteType;
    }
}