package com.work.shop.oms.bean;

public class SystemMsgTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_msg_template.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_msg_template.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_msg_template.template
     *
     * @mbggenerated
     */
    private String template;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_msg_template.code
     *
     * @return the value of system_msg_template.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_msg_template.code
     *
     * @param code the value for system_msg_template.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_msg_template.name
     *
     * @return the value of system_msg_template.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_msg_template.name
     *
     * @param name the value for system_msg_template.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_msg_template.template
     *
     * @return the value of system_msg_template.template
     *
     * @mbggenerated
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_msg_template.template
     *
     * @param template the value for system_msg_template.template
     *
     * @mbggenerated
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }
}