package com.work.shop.oms.bean;

public class SystemConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.parent_id
     *
     * @mbggenerated
     */
    private Short parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.store_range
     *
     * @mbggenerated
     */
    private String storeRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.store_range_name
     *
     * @mbggenerated
     */
    private String storeRangeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.store_dir
     *
     * @mbggenerated
     */
    private String storeDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.sort_order
     *
     * @mbggenerated
     */
    private Byte sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.parent_id
     *
     * @return the value of system_config.parent_id
     *
     * @mbggenerated
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.parent_id
     *
     * @param parentId the value for system_config.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.code
     *
     * @return the value of system_config.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.code
     *
     * @param code the value for system_config.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.name
     *
     * @return the value of system_config.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.name
     *
     * @param name the value for system_config.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.type
     *
     * @return the value of system_config.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.type
     *
     * @param type the value for system_config.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.store_range
     *
     * @return the value of system_config.store_range
     *
     * @mbggenerated
     */
    public String getStoreRange() {
        return storeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.store_range
     *
     * @param storeRange the value for system_config.store_range
     *
     * @mbggenerated
     */
    public void setStoreRange(String storeRange) {
        this.storeRange = storeRange == null ? null : storeRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.store_range_name
     *
     * @return the value of system_config.store_range_name
     *
     * @mbggenerated
     */
    public String getStoreRangeName() {
        return storeRangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.store_range_name
     *
     * @param storeRangeName the value for system_config.store_range_name
     *
     * @mbggenerated
     */
    public void setStoreRangeName(String storeRangeName) {
        this.storeRangeName = storeRangeName == null ? null : storeRangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.store_dir
     *
     * @return the value of system_config.store_dir
     *
     * @mbggenerated
     */
    public String getStoreDir() {
        return storeDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.store_dir
     *
     * @param storeDir the value for system_config.store_dir
     *
     * @mbggenerated
     */
    public void setStoreDir(String storeDir) {
        this.storeDir = storeDir == null ? null : storeDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.sort_order
     *
     * @return the value of system_config.sort_order
     *
     * @mbggenerated
     */
    public Byte getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.sort_order
     *
     * @param sortOrder the value for system_config.sort_order
     *
     * @mbggenerated
     */
    public void setSortOrder(Byte sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.value
     *
     * @return the value of system_config.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.value
     *
     * @param value the value for system_config.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}