package com.work.shop.oms.bean;

import java.util.ArrayList;
import java.util.List;

public class SystemAreaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_area
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_area
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_area
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public SystemAreaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_area
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**  
         * limit 
         * 
         */ 
        public Criteria limit(int offset, int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit",offset,len,"null");
            return (Criteria) this;
        }

        /**  
         * top 
         * 
         */ 
        public Criteria limit(int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit", 0, len, "null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("area_id like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("area_id not like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIsNull() {
            addCriterion("area_type is null");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIsNotNull() {
            addCriterion("area_type is not null");
            return (Criteria) this;
        }

        public Criteria andAreaTypeEqualTo(String value) {
            addCriterion("area_type =", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotEqualTo(String value) {
            addCriterion("area_type <>", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeGreaterThan(String value) {
            addCriterion("area_type >", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeGreaterThanOrEqualTo(String value) {
            addCriterion("area_type >=", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeLessThan(String value) {
            addCriterion("area_type <", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeLessThanOrEqualTo(String value) {
            addCriterion("area_type <=", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeLike(String value) {
            addCriterion("area_type like", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotLike(String value) {
            addCriterion("area_type not like", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIn(List<String> values) {
            addCriterion("area_type in", values, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotIn(List<String> values) {
            addCriterion("area_type not in", values, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeBetween(String value1, String value2) {
            addCriterion("area_type between", value1, value2, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotBetween(String value1, String value2) {
            addCriterion("area_type not between", value1, value2, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNull() {
            addCriterion("area_name is null");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNotNull() {
            addCriterion("area_name is not null");
            return (Criteria) this;
        }

        public Criteria andAreaNameEqualTo(String value) {
            addCriterion("area_name =", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotEqualTo(String value) {
            addCriterion("area_name <>", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThan(String value) {
            addCriterion("area_name >", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThanOrEqualTo(String value) {
            addCriterion("area_name >=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThan(String value) {
            addCriterion("area_name <", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThanOrEqualTo(String value) {
            addCriterion("area_name <=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLike(String value) {
            addCriterion("area_name like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotLike(String value) {
            addCriterion("area_name not like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameIn(List<String> values) {
            addCriterion("area_name in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotIn(List<String> values) {
            addCriterion("area_name not in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameBetween(String value1, String value2) {
            addCriterion("area_name between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotBetween(String value1, String value2) {
            addCriterion("area_name not between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andSystemAreaIsNull() {
            addCriterion("system_area is null");
            return (Criteria) this;
        }

        public Criteria andSystemAreaIsNotNull() {
            addCriterion("system_area is not null");
            return (Criteria) this;
        }

        public Criteria andSystemAreaEqualTo(Integer value) {
            addCriterion("system_area =", value, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaNotEqualTo(Integer value) {
            addCriterion("system_area <>", value, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaGreaterThan(Integer value) {
            addCriterion("system_area >", value, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_area >=", value, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaLessThan(Integer value) {
            addCriterion("system_area <", value, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaLessThanOrEqualTo(Integer value) {
            addCriterion("system_area <=", value, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaIn(List<Integer> values) {
            addCriterion("system_area in", values, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaNotIn(List<Integer> values) {
            addCriterion("system_area not in", values, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaBetween(Integer value1, Integer value2) {
            addCriterion("system_area between", value1, value2, "systemArea");
            return (Criteria) this;
        }

        public Criteria andSystemAreaNotBetween(Integer value1, Integer value2) {
            addCriterion("system_area not between", value1, value2, "systemArea");
            return (Criteria) this;
        }

        public Criteria andZipIsNull() {
            addCriterion("zip is null");
            return (Criteria) this;
        }

        public Criteria andZipIsNotNull() {
            addCriterion("zip is not null");
            return (Criteria) this;
        }

        public Criteria andZipEqualTo(String value) {
            addCriterion("zip =", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotEqualTo(String value) {
            addCriterion("zip <>", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThan(String value) {
            addCriterion("zip >", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThanOrEqualTo(String value) {
            addCriterion("zip >=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThan(String value) {
            addCriterion("zip <", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThanOrEqualTo(String value) {
            addCriterion("zip <=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLike(String value) {
            addCriterion("zip like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotLike(String value) {
            addCriterion("zip not like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipIn(List<String> values) {
            addCriterion("zip in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotIn(List<String> values) {
            addCriterion("zip not in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipBetween(String value1, String value2) {
            addCriterion("zip between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotBetween(String value1, String value2) {
            addCriterion("zip not between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdIsNull() {
            addCriterion("os_region_id is null");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdIsNotNull() {
            addCriterion("os_region_id is not null");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdEqualTo(String value) {
            addCriterion("os_region_id =", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdNotEqualTo(String value) {
            addCriterion("os_region_id <>", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdGreaterThan(String value) {
            addCriterion("os_region_id >", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdGreaterThanOrEqualTo(String value) {
            addCriterion("os_region_id >=", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdLessThan(String value) {
            addCriterion("os_region_id <", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdLessThanOrEqualTo(String value) {
            addCriterion("os_region_id <=", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdLike(String value) {
            addCriterion("os_region_id like", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdNotLike(String value) {
            addCriterion("os_region_id not like", value, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdIn(List<String> values) {
            addCriterion("os_region_id in", values, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdNotIn(List<String> values) {
            addCriterion("os_region_id not in", values, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdBetween(String value1, String value2) {
            addCriterion("os_region_id between", value1, value2, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionIdNotBetween(String value1, String value2) {
            addCriterion("os_region_id not between", value1, value2, "osRegionId");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameIsNull() {
            addCriterion("os_region_name is null");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameIsNotNull() {
            addCriterion("os_region_name is not null");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameEqualTo(String value) {
            addCriterion("os_region_name =", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameNotEqualTo(String value) {
            addCriterion("os_region_name <>", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameGreaterThan(String value) {
            addCriterion("os_region_name >", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameGreaterThanOrEqualTo(String value) {
            addCriterion("os_region_name >=", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameLessThan(String value) {
            addCriterion("os_region_name <", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameLessThanOrEqualTo(String value) {
            addCriterion("os_region_name <=", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameLike(String value) {
            addCriterion("os_region_name like", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameNotLike(String value) {
            addCriterion("os_region_name not like", value, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameIn(List<String> values) {
            addCriterion("os_region_name in", values, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameNotIn(List<String> values) {
            addCriterion("os_region_name not in", values, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameBetween(String value1, String value2) {
            addCriterion("os_region_name between", value1, value2, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andOsRegionNameNotBetween(String value1, String value2) {
            addCriterion("os_region_name not between", value1, value2, "osRegionName");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNull() {
            addCriterion("channel_code is null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNotNull() {
            addCriterion("channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeEqualTo(String value) {
            addCriterion("channel_code =", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotEqualTo(String value) {
            addCriterion("channel_code <>", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThan(String value) {
            addCriterion("channel_code >", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("channel_code >=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThan(String value) {
            addCriterion("channel_code <", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("channel_code <=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLike(String value) {
            addCriterion("channel_code like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotLike(String value) {
            addCriterion("channel_code not like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIn(List<String> values) {
            addCriterion("channel_code in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotIn(List<String> values) {
            addCriterion("channel_code not in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeBetween(String value1, String value2) {
            addCriterion("channel_code between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotBetween(String value1, String value2) {
            addCriterion("channel_code not between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeIsNull() {
            addCriterion("shop_code is null");
            return (Criteria) this;
        }

        public Criteria andShopCodeIsNotNull() {
            addCriterion("shop_code is not null");
            return (Criteria) this;
        }

        public Criteria andShopCodeEqualTo(String value) {
            addCriterion("shop_code =", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeNotEqualTo(String value) {
            addCriterion("shop_code <>", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeGreaterThan(String value) {
            addCriterion("shop_code >", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeGreaterThanOrEqualTo(String value) {
            addCriterion("shop_code >=", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeLessThan(String value) {
            addCriterion("shop_code <", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeLessThanOrEqualTo(String value) {
            addCriterion("shop_code <=", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeLike(String value) {
            addCriterion("shop_code like", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeNotLike(String value) {
            addCriterion("shop_code not like", value, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeIn(List<String> values) {
            addCriterion("shop_code in", values, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeNotIn(List<String> values) {
            addCriterion("shop_code not in", values, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeBetween(String value1, String value2) {
            addCriterion("shop_code between", value1, value2, "shopCode");
            return (Criteria) this;
        }

        public Criteria andShopCodeNotBetween(String value1, String value2) {
            addCriterion("shop_code not between", value1, value2, "shopCode");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIsNull() {
            addCriterion("match_type is null");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIsNotNull() {
            addCriterion("match_type is not null");
            return (Criteria) this;
        }

        public Criteria andMatchTypeEqualTo(Integer value) {
            addCriterion("match_type =", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotEqualTo(Integer value) {
            addCriterion("match_type <>", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeGreaterThan(Integer value) {
            addCriterion("match_type >", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("match_type >=", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLessThan(Integer value) {
            addCriterion("match_type <", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLessThanOrEqualTo(Integer value) {
            addCriterion("match_type <=", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIn(List<Integer> values) {
            addCriterion("match_type in", values, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotIn(List<Integer> values) {
            addCriterion("match_type not in", values, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeBetween(Integer value1, Integer value2) {
            addCriterion("match_type between", value1, value2, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("match_type not between", value1, value2, "matchType");
            return (Criteria) this;
        }

        public Criteria andPareaCodeIsNull() {
            addCriterion("parea_code is null");
            return (Criteria) this;
        }

        public Criteria andPareaCodeIsNotNull() {
            addCriterion("parea_code is not null");
            return (Criteria) this;
        }

        public Criteria andPareaCodeEqualTo(String value) {
            addCriterion("parea_code =", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeNotEqualTo(String value) {
            addCriterion("parea_code <>", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeGreaterThan(String value) {
            addCriterion("parea_code >", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("parea_code >=", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeLessThan(String value) {
            addCriterion("parea_code <", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeLessThanOrEqualTo(String value) {
            addCriterion("parea_code <=", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeLike(String value) {
            addCriterion("parea_code like", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeNotLike(String value) {
            addCriterion("parea_code not like", value, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeIn(List<String> values) {
            addCriterion("parea_code in", values, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeNotIn(List<String> values) {
            addCriterion("parea_code not in", values, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeBetween(String value1, String value2) {
            addCriterion("parea_code between", value1, value2, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andPareaCodeNotBetween(String value1, String value2) {
            addCriterion("parea_code not between", value1, value2, "pareaCode");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasIsNull() {
            addCriterion("area_name_alias is null");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasIsNotNull() {
            addCriterion("area_name_alias is not null");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasEqualTo(String value) {
            addCriterion("area_name_alias =", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasNotEqualTo(String value) {
            addCriterion("area_name_alias <>", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasGreaterThan(String value) {
            addCriterion("area_name_alias >", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasGreaterThanOrEqualTo(String value) {
            addCriterion("area_name_alias >=", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasLessThan(String value) {
            addCriterion("area_name_alias <", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasLessThanOrEqualTo(String value) {
            addCriterion("area_name_alias <=", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasLike(String value) {
            addCriterion("area_name_alias like", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasNotLike(String value) {
            addCriterion("area_name_alias not like", value, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasIn(List<String> values) {
            addCriterion("area_name_alias in", values, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasNotIn(List<String> values) {
            addCriterion("area_name_alias not in", values, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasBetween(String value1, String value2) {
            addCriterion("area_name_alias between", value1, value2, "areaNameAlias");
            return (Criteria) this;
        }

        public Criteria andAreaNameAliasNotBetween(String value1, String value2) {
            addCriterion("area_name_alias not between", value1, value2, "areaNameAlias");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_area
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_area
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}