package com.work.shop.oms.bean;

import java.math.BigDecimal;
import java.util.Date;

public class UserPointsException {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.option_type
     *
     * @mbggenerated
     */
    private String optionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.points
     *
     * @mbggenerated
     */
    private BigDecimal points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.submit_param
     *
     * @mbggenerated
     */
    private String submitParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.process_type
     *
     * @mbggenerated
     */
    private Integer processType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_points_exception.option_note
     *
     * @mbggenerated
     */
    private String optionNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.id
     *
     * @return the value of user_points_exception.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.id
     *
     * @param id the value for user_points_exception.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.order_sn
     *
     * @return the value of user_points_exception.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.order_sn
     *
     * @param orderSn the value for user_points_exception.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.option_type
     *
     * @return the value of user_points_exception.option_type
     *
     * @mbggenerated
     */
    public String getOptionType() {
        return optionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.option_type
     *
     * @param optionType the value for user_points_exception.option_type
     *
     * @mbggenerated
     */
    public void setOptionType(String optionType) {
        this.optionType = optionType == null ? null : optionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.user_id
     *
     * @return the value of user_points_exception.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.user_id
     *
     * @param userId the value for user_points_exception.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.points
     *
     * @return the value of user_points_exception.points
     *
     * @mbggenerated
     */
    public BigDecimal getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.points
     *
     * @param points the value for user_points_exception.points
     *
     * @mbggenerated
     */
    public void setPoints(BigDecimal points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.submit_param
     *
     * @return the value of user_points_exception.submit_param
     *
     * @mbggenerated
     */
    public String getSubmitParam() {
        return submitParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.submit_param
     *
     * @param submitParam the value for user_points_exception.submit_param
     *
     * @mbggenerated
     */
    public void setSubmitParam(String submitParam) {
        this.submitParam = submitParam == null ? null : submitParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.create_time
     *
     * @return the value of user_points_exception.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.create_time
     *
     * @param createTime the value for user_points_exception.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.process_type
     *
     * @return the value of user_points_exception.process_type
     *
     * @mbggenerated
     */
    public Integer getProcessType() {
        return processType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.process_type
     *
     * @param processType the value for user_points_exception.process_type
     *
     * @mbggenerated
     */
    public void setProcessType(Integer processType) {
        this.processType = processType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_points_exception.option_note
     *
     * @return the value of user_points_exception.option_note
     *
     * @mbggenerated
     */
    public String getOptionNote() {
        return optionNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_points_exception.option_note
     *
     * @param optionNote the value for user_points_exception.option_note
     *
     * @mbggenerated
     */
    public void setOptionNote(String optionNote) {
        this.optionNote = optionNote == null ? null : optionNote.trim();
    }
}