package com.work.shop.oms.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WkSfGdnExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public WkSfGdnExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**  
         * limit 
         * 
         */ 
        public Criteria limit(int offset, int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit",offset,len,"null");
            return (Criteria) this;
        }

        /**  
         * top 
         * 
         */ 
        public Criteria limit(int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit", 0, len, "null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWkIdIsNull() {
            addCriterion("wk_id is null");
            return (Criteria) this;
        }

        public Criteria andWkIdIsNotNull() {
            addCriterion("wk_id is not null");
            return (Criteria) this;
        }

        public Criteria andWkIdEqualTo(Integer value) {
            addCriterion("wk_id =", value, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdNotEqualTo(Integer value) {
            addCriterion("wk_id <>", value, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdGreaterThan(Integer value) {
            addCriterion("wk_id >", value, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wk_id >=", value, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdLessThan(Integer value) {
            addCriterion("wk_id <", value, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdLessThanOrEqualTo(Integer value) {
            addCriterion("wk_id <=", value, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdIn(List<Integer> values) {
            addCriterion("wk_id in", values, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdNotIn(List<Integer> values) {
            addCriterion("wk_id not in", values, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdBetween(Integer value1, Integer value2) {
            addCriterion("wk_id between", value1, value2, "wkId");
            return (Criteria) this;
        }

        public Criteria andWkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wk_id not between", value1, value2, "wkId");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOuterCodeIsNull() {
            addCriterion("outer_code is null");
            return (Criteria) this;
        }

        public Criteria andOuterCodeIsNotNull() {
            addCriterion("outer_code is not null");
            return (Criteria) this;
        }

        public Criteria andOuterCodeEqualTo(String value) {
            addCriterion("outer_code =", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeNotEqualTo(String value) {
            addCriterion("outer_code <>", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeGreaterThan(String value) {
            addCriterion("outer_code >", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("outer_code >=", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeLessThan(String value) {
            addCriterion("outer_code <", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeLessThanOrEqualTo(String value) {
            addCriterion("outer_code <=", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeLike(String value) {
            addCriterion("outer_code like", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeNotLike(String value) {
            addCriterion("outer_code not like", value, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeIn(List<String> values) {
            addCriterion("outer_code in", values, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeNotIn(List<String> values) {
            addCriterion("outer_code not in", values, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeBetween(String value1, String value2) {
            addCriterion("outer_code between", value1, value2, "outerCode");
            return (Criteria) this;
        }

        public Criteria andOuterCodeNotBetween(String value1, String value2) {
            addCriterion("outer_code not between", value1, value2, "outerCode");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdIsNull() {
            addCriterion("bf_org_wareh_id is null");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdIsNotNull() {
            addCriterion("bf_org_wareh_id is not null");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdEqualTo(Integer value) {
            addCriterion("bf_org_wareh_id =", value, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdNotEqualTo(Integer value) {
            addCriterion("bf_org_wareh_id <>", value, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdGreaterThan(Integer value) {
            addCriterion("bf_org_wareh_id >", value, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bf_org_wareh_id >=", value, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdLessThan(Integer value) {
            addCriterion("bf_org_wareh_id <", value, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdLessThanOrEqualTo(Integer value) {
            addCriterion("bf_org_wareh_id <=", value, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdIn(List<Integer> values) {
            addCriterion("bf_org_wareh_id in", values, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdNotIn(List<Integer> values) {
            addCriterion("bf_org_wareh_id not in", values, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdBetween(Integer value1, Integer value2) {
            addCriterion("bf_org_wareh_id between", value1, value2, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andBfOrgWarehIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bf_org_wareh_id not between", value1, value2, "bfOrgWarehId");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeIsNull() {
            addCriterion("dist_wareh_code is null");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeIsNotNull() {
            addCriterion("dist_wareh_code is not null");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeEqualTo(String value) {
            addCriterion("dist_wareh_code =", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeNotEqualTo(String value) {
            addCriterion("dist_wareh_code <>", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeGreaterThan(String value) {
            addCriterion("dist_wareh_code >", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dist_wareh_code >=", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeLessThan(String value) {
            addCriterion("dist_wareh_code <", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeLessThanOrEqualTo(String value) {
            addCriterion("dist_wareh_code <=", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeLike(String value) {
            addCriterion("dist_wareh_code like", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeNotLike(String value) {
            addCriterion("dist_wareh_code not like", value, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeIn(List<String> values) {
            addCriterion("dist_wareh_code in", values, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeNotIn(List<String> values) {
            addCriterion("dist_wareh_code not in", values, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeBetween(String value1, String value2) {
            addCriterion("dist_wareh_code between", value1, value2, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andDistWarehCodeNotBetween(String value1, String value2) {
            addCriterion("dist_wareh_code not between", value1, value2, "distWarehCode");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("region_id is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("region_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(Short value) {
            addCriterion("region_id =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(Short value) {
            addCriterion("region_id <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(Short value) {
            addCriterion("region_id >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(Short value) {
            addCriterion("region_id >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(Short value) {
            addCriterion("region_id <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(Short value) {
            addCriterion("region_id <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<Short> values) {
            addCriterion("region_id in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<Short> values) {
            addCriterion("region_id not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(Short value1, Short value2) {
            addCriterion("region_id between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(Short value1, Short value2) {
            addCriterion("region_id not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andTtlQtyIsNull() {
            addCriterion("ttl_qty is null");
            return (Criteria) this;
        }

        public Criteria andTtlQtyIsNotNull() {
            addCriterion("ttl_qty is not null");
            return (Criteria) this;
        }

        public Criteria andTtlQtyEqualTo(Integer value) {
            addCriterion("ttl_qty =", value, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyNotEqualTo(Integer value) {
            addCriterion("ttl_qty <>", value, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyGreaterThan(Integer value) {
            addCriterion("ttl_qty >", value, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("ttl_qty >=", value, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyLessThan(Integer value) {
            addCriterion("ttl_qty <", value, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyLessThanOrEqualTo(Integer value) {
            addCriterion("ttl_qty <=", value, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyIn(List<Integer> values) {
            addCriterion("ttl_qty in", values, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyNotIn(List<Integer> values) {
            addCriterion("ttl_qty not in", values, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyBetween(Integer value1, Integer value2) {
            addCriterion("ttl_qty between", value1, value2, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andTtlQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("ttl_qty not between", value1, value2, "ttlQty");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdIsNull() {
            addCriterion("bf_org_tsp_com_id is null");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdIsNotNull() {
            addCriterion("bf_org_tsp_com_id is not null");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdEqualTo(Integer value) {
            addCriterion("bf_org_tsp_com_id =", value, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdNotEqualTo(Integer value) {
            addCriterion("bf_org_tsp_com_id <>", value, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdGreaterThan(Integer value) {
            addCriterion("bf_org_tsp_com_id >", value, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bf_org_tsp_com_id >=", value, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdLessThan(Integer value) {
            addCriterion("bf_org_tsp_com_id <", value, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdLessThanOrEqualTo(Integer value) {
            addCriterion("bf_org_tsp_com_id <=", value, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdIn(List<Integer> values) {
            addCriterion("bf_org_tsp_com_id in", values, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdNotIn(List<Integer> values) {
            addCriterion("bf_org_tsp_com_id not in", values, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdBetween(Integer value1, Integer value2) {
            addCriterion("bf_org_tsp_com_id between", value1, value2, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andBfOrgTspComIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bf_org_tsp_com_id not between", value1, value2, "bfOrgTspComId");
            return (Criteria) this;
        }

        public Criteria andShipCodeIsNull() {
            addCriterion("ship_code is null");
            return (Criteria) this;
        }

        public Criteria andShipCodeIsNotNull() {
            addCriterion("ship_code is not null");
            return (Criteria) this;
        }

        public Criteria andShipCodeEqualTo(String value) {
            addCriterion("ship_code =", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeNotEqualTo(String value) {
            addCriterion("ship_code <>", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeGreaterThan(String value) {
            addCriterion("ship_code >", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ship_code >=", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeLessThan(String value) {
            addCriterion("ship_code <", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeLessThanOrEqualTo(String value) {
            addCriterion("ship_code <=", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeLike(String value) {
            addCriterion("ship_code like", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeNotLike(String value) {
            addCriterion("ship_code not like", value, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeIn(List<String> values) {
            addCriterion("ship_code in", values, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeNotIn(List<String> values) {
            addCriterion("ship_code not in", values, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeBetween(String value1, String value2) {
            addCriterion("ship_code between", value1, value2, "shipCode");
            return (Criteria) this;
        }

        public Criteria andShipCodeNotBetween(String value1, String value2) {
            addCriterion("ship_code not between", value1, value2, "shipCode");
            return (Criteria) this;
        }

        public Criteria andCsbNumIsNull() {
            addCriterion("csb_num is null");
            return (Criteria) this;
        }

        public Criteria andCsbNumIsNotNull() {
            addCriterion("csb_num is not null");
            return (Criteria) this;
        }

        public Criteria andCsbNumEqualTo(String value) {
            addCriterion("csb_num =", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumNotEqualTo(String value) {
            addCriterion("csb_num <>", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumGreaterThan(String value) {
            addCriterion("csb_num >", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumGreaterThanOrEqualTo(String value) {
            addCriterion("csb_num >=", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumLessThan(String value) {
            addCriterion("csb_num <", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumLessThanOrEqualTo(String value) {
            addCriterion("csb_num <=", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumLike(String value) {
            addCriterion("csb_num like", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumNotLike(String value) {
            addCriterion("csb_num not like", value, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumIn(List<String> values) {
            addCriterion("csb_num in", values, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumNotIn(List<String> values) {
            addCriterion("csb_num not in", values, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumBetween(String value1, String value2) {
            addCriterion("csb_num between", value1, value2, "csbNum");
            return (Criteria) this;
        }

        public Criteria andCsbNumNotBetween(String value1, String value2) {
            addCriterion("csb_num not between", value1, value2, "csbNum");
            return (Criteria) this;
        }

        public Criteria andShipDateIsNull() {
            addCriterion("ship_date is null");
            return (Criteria) this;
        }

        public Criteria andShipDateIsNotNull() {
            addCriterion("ship_date is not null");
            return (Criteria) this;
        }

        public Criteria andShipDateEqualTo(Date value) {
            addCriterion("ship_date =", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotEqualTo(Date value) {
            addCriterion("ship_date <>", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateGreaterThan(Date value) {
            addCriterion("ship_date >", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ship_date >=", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateLessThan(Date value) {
            addCriterion("ship_date <", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateLessThanOrEqualTo(Date value) {
            addCriterion("ship_date <=", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateIn(List<Date> values) {
            addCriterion("ship_date in", values, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotIn(List<Date> values) {
            addCriterion("ship_date not in", values, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateBetween(Date value1, Date value2) {
            addCriterion("ship_date between", value1, value2, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotBetween(Date value1, Date value2) {
            addCriterion("ship_date not between", value1, value2, "shipDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("last_modified_date is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("last_modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("last_modified_date =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("last_modified_date <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("last_modified_date >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_modified_date >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("last_modified_date <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("last_modified_date <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("last_modified_date in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("last_modified_date not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("last_modified_date between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("last_modified_date not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeIsNull() {
            addCriterion("major_send_wareh_code is null");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeIsNotNull() {
            addCriterion("major_send_wareh_code is not null");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeEqualTo(String value) {
            addCriterion("major_send_wareh_code =", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeNotEqualTo(String value) {
            addCriterion("major_send_wareh_code <>", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeGreaterThan(String value) {
            addCriterion("major_send_wareh_code >", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeGreaterThanOrEqualTo(String value) {
            addCriterion("major_send_wareh_code >=", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeLessThan(String value) {
            addCriterion("major_send_wareh_code <", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeLessThanOrEqualTo(String value) {
            addCriterion("major_send_wareh_code <=", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeLike(String value) {
            addCriterion("major_send_wareh_code like", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeNotLike(String value) {
            addCriterion("major_send_wareh_code not like", value, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeIn(List<String> values) {
            addCriterion("major_send_wareh_code in", values, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeNotIn(List<String> values) {
            addCriterion("major_send_wareh_code not in", values, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeBetween(String value1, String value2) {
            addCriterion("major_send_wareh_code between", value1, value2, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andMajorSendWarehCodeNotBetween(String value1, String value2) {
            addCriterion("major_send_wareh_code not between", value1, value2, "majorSendWarehCode");
            return (Criteria) this;
        }

        public Criteria andShipTypeIsNull() {
            addCriterion("ship_type is null");
            return (Criteria) this;
        }

        public Criteria andShipTypeIsNotNull() {
            addCriterion("ship_type is not null");
            return (Criteria) this;
        }

        public Criteria andShipTypeEqualTo(Integer value) {
            addCriterion("ship_type =", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeNotEqualTo(Integer value) {
            addCriterion("ship_type <>", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeGreaterThan(Integer value) {
            addCriterion("ship_type >", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ship_type >=", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeLessThan(Integer value) {
            addCriterion("ship_type <", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeLessThanOrEqualTo(Integer value) {
            addCriterion("ship_type <=", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeIn(List<Integer> values) {
            addCriterion("ship_type in", values, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeNotIn(List<Integer> values) {
            addCriterion("ship_type not in", values, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeBetween(Integer value1, Integer value2) {
            addCriterion("ship_type between", value1, value2, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ship_type not between", value1, value2, "shipType");
            return (Criteria) this;
        }

        public Criteria andSynFlagIsNull() {
            addCriterion("syn_flag is null");
            return (Criteria) this;
        }

        public Criteria andSynFlagIsNotNull() {
            addCriterion("syn_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSynFlagEqualTo(Integer value) {
            addCriterion("syn_flag =", value, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagNotEqualTo(Integer value) {
            addCriterion("syn_flag <>", value, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagGreaterThan(Integer value) {
            addCriterion("syn_flag >", value, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("syn_flag >=", value, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagLessThan(Integer value) {
            addCriterion("syn_flag <", value, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagLessThanOrEqualTo(Integer value) {
            addCriterion("syn_flag <=", value, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagIn(List<Integer> values) {
            addCriterion("syn_flag in", values, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagNotIn(List<Integer> values) {
            addCriterion("syn_flag not in", values, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagBetween(Integer value1, Integer value2) {
            addCriterion("syn_flag between", value1, value2, "synFlag");
            return (Criteria) this;
        }

        public Criteria andSynFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("syn_flag not between", value1, value2, "synFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wk_sf_gdn
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}